import { test } from "node:test";
import assert from "node:assert/strict";
import { createRustBackend, planCargoManifest, printCargoManifest } from "../dist/index.js";
import { fakeCompileInput, fakeSourceFile } from "./helpers/fake-compile-input.mjs";

const backendContext = {
  project: { entryPoint: "src/index.ts", targets: [] },
  target: { id: "rust", options: {} },
};

function runtimeReference(crate, path) {
  return { kind: "cargo-path", include: path, attributes: { crate } };
}

test("empty program emits a deterministic cargo library project", () => {
  const backend = createRustBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    sourceFiles: [fakeSourceFile({ fileName: "src/empty.ts", text: "", statements: [] })],
    runtimeReferences: [runtimeReference("tsonic_rust_runtime", "/repos/rust-runtime/crates/tsonic_rust_runtime")],
  }));

  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.artifacts.map((artifact) => [artifact.kind, artifact.path]), [
    ["project", "Cargo.toml"],
    ["source", "src/lib.rs"],
    ["source", "src/empty.rs"],
  ]);
  const manifest = result.artifacts[0].text;
  assert.equal(manifest, [
    "[package]",
    'name = "tsonic_generated"',
    'version = "0.1.0"',
    'edition = "2021"',
    "",
    "[dependencies]",
    'tsonic_rust_runtime = { path = "/repos/rust-runtime/crates/tsonic_rust_runtime" }',
    "",
  ].join("\n"));
  const librarySource = result.artifacts[1];
  assert.equal(librarySource.language, "rust");
  assert.equal(librarySource.text, [
    "// Generated by the Tsonic Rust target. Do not edit.",
    "",
    "pub mod empty;",
    "",
  ].join("\n"));
  assert.equal(result.artifacts[2].text, "// Generated by the Tsonic Rust target. Do not edit.\n");
});

test("bin output without an exported entry main fails closed", () => {
  const backend = createRustBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    target: { id: "rust", options: { outputType: "bin", crateName: "my_app", edition: "2024" } },
    runtimeReferences: [runtimeReference("tsonic_rust_runtime", "/repos/rust-runtime/crates/tsonic_rust_runtime")],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.ok(result.diagnostics.some((diagnostic) => diagnostic.code === "RUST_MISSING_ENTRYPOINT"));
});

test("cargo dependencies are sorted and deduplicated deterministically", () => {
  const plan = planCargoManifest({ id: "rust", options: {} }, [
    runtimeReference("tsonic_rust_runtime", "/repos/rust-runtime/crates/tsonic_rust_runtime"),
    runtimeReference("tsonic_rust_js", "/repos/rust-js/crates/tsonic_rust_js"),
    runtimeReference("tsonic_rust_runtime", "/repos/rust-runtime/crates/tsonic_rust_runtime"),
  ]);

  assert.deepEqual(plan.diagnostics, []);
  assert.deepEqual(plan.manifest.dependencies.map((dependency) => dependency.name), [
    "tsonic_rust_js",
    "tsonic_rust_runtime",
  ]);
});

test("unknown runtime reference kinds fail closed without artifacts", () => {
  const backend = createRustBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    runtimeReferences: [{ kind: "project", include: "/repos/x/x.csproj" }],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "RUST_UNSUPPORTED_RUNTIME_REFERENCE");
});

test("conflicting crate paths for the same crate name fail closed", () => {
  const plan = planCargoManifest({ id: "rust", options: {} }, [
    runtimeReference("tsonic_rust_runtime", "/repos/a/tsonic_rust_runtime"),
    runtimeReference("tsonic_rust_runtime", "/repos/b/tsonic_rust_runtime"),
  ]);

  assert.equal(plan.manifest, undefined);
  assert.equal(plan.diagnostics.length, 1);
});

test("toml strings escape quotes and backslashes", () => {
  const text = printCargoManifest({
    packageName: "tsonic_generated",
    edition: "2021",
    outputType: "lib",
    dependencies: [{ name: "dep", path: 'C:\\repos\\"odd"' }],
  });

  assert.match(text, /dep = \{ path = "C:\\\\repos\\\\\\"odd\\"" \}/);
});
