import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("fitting method-call arguments remain on one rustfmt line", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "method-call",
              receiver: {
                kind: "call",
                path: "tsonic_rust_node::process::env_get",
                args: [{ kind: "str-literal", value: "R7_UNSET_VAR_PROOF" }],
              },
              method: "is_none",
              args: [],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /acme_testing::check\(tsonic_rust_node::process::env_get\("R7_UNSET_VAR_PROOF"\)\.is_none\(\)\);/u,
  );
});

test("method chains inside expanded call comparisons use argument indentation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "pair.load",
                  args: [],
                },
                method: "addLeft",
                args: [{
                  kind: "method-call",
                  receiver: {
                    kind: "field",
                    receiver: {
                      kind: "call",
                      path: "pair.load",
                      args: [],
                    },
                    name: "__tsonic_state",
                  },
                  method: "with",
                  args: [{
                    kind: "closure",
                    params: [{ name: "state", byRefCopy: false }],
                    body: { kind: "path", path: "state.1" },
                  }],
                }],
              },
              right: { kind: "int-literal", text: "10" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(\n        pair\.load\(\)\n            \.addLeft/u);
});

test("field and closure method chains retain rustfmt vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "field",
              receiver: { kind: "path", path: "__tsonic_receiver" },
              name: "__tsonic_state",
            },
            method: "with_mut",
            args: [{
              kind: "closure",
              params: [{ name: "state", byRefCopy: false }],
              body: {
                kind: "binary",
                operator: "+=",
                left: { kind: "path", path: "state.0" },
                right: { kind: "path", path: "__tsonic_value" },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /__tsonic_receiver\n        \.__tsonic_state\n        \.with_mut/u,
  );
});

test("two-selector method arguments retain rustfmt vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "values" },
                method: "get",
                args: [{
                  kind: "try",
                  expr: {
                    kind: "call",
                    path: "tsonic_rust_runtime::conversions::i32_to_usize",
                    args: [{ kind: "int-literal", text: "1" }],
                  },
                }],
              },
              method: "is_none",
              args: [],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(\n        values\n            \.get/u);
});

test("selectors after multiline call bases align with the base", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "read",
                  args: [{
                    kind: "struct-literal",
                    path: "Box",
                    fields: [
                      { name: "left", value: { kind: "int-literal", text: "1" } },
                      { name: "middle", value: { kind: "int-literal", text: "2" } },
                      { name: "right", value: { kind: "int-literal", text: "3" } },
                    ],
                  }],
                },
                method: "unwrap_or",
                args: [{ kind: "int-literal", text: "-1" }],
              },
              right: { kind: "int-literal", text: "7" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /\n        \.unwrap_or\(-1\)/u);
  assert.doesNotMatch(source, /\n            \.unwrap_or\(-1\)/u);
});

test("long multiline let initializers reflow from their continuation column", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "textFunction",
          mutable: false,
          init: {
            kind: "associated-call",
            owner: {
              kind: "named",
              path: "rt::Callable",
              typeArguments: [
                { kind: "tuple", elements: [{ kind: "string" }] },
                { kind: "string" },
              ],
            },
            method: "new",
            args: [{
              kind: "closure-block",
              params: [{
                name: "__tsonic_callable_arguments_5",
                mutable: false,
              }],
              move: true,
              async: false,
              body: {
                statements: [{
                  kind: "tail",
                  expr: {
                    kind: "call",
                    path: "preserveText",
                    args: [{
                      kind: "field",
                      receiver: { kind: "path", path: "__tsonic_callable_arguments_5" },
                      name: "0",
                    }],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let textFunction =\n        rt::Callable::<\(String,\), String>::new\(move \|__tsonic_callable_arguments_5\| \{/u,
  );
});

test("long expression closures use a vertical receiver before expanding the closure body", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "bool-literal", value: true },
          then: {
            statements: [{
              kind: "if",
              condition: { kind: "bool-literal", value: true },
              then: {
                statements: [{
                  kind: "expr",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "__tsonic_capture_visits" },
                    method: "update_with",
                    args: [{
                      kind: "closure",
                      params: [{ name: "__tsonic_location_current", byRefCopy: false }],
                      body: {
                        kind: "binary",
                        operator: "+",
                        left: { kind: "path", path: "__tsonic_location_current" },
                        right: { kind: "int-literal", text: "1" },
                      },
                    }],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /__tsonic_capture_visits\n                \.update_with\(\|__tsonic_location_current\| __tsonic_location_current \+ 1\);/u,
  );
});

test("short optional chains stay attached when their fitted closure body expands", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: { kind: "path", path: "item" },
              method: "as_ref",
              args: [],
            },
            method: "map",
            args: [{
              kind: "closure",
              params: [{ name: "__tsonic_optional_receiver", byRefCopy: false }],
              body: {
                kind: "method-call",
                receiver: {
                  kind: "field",
                  receiver: { kind: "path", path: "__tsonic_optional_receiver" },
                  name: "__tsonic_state",
                },
                method: "with",
                args: [{
                  kind: "closure",
                  params: [{ name: "state", byRefCopy: false }],
                  body: { kind: "field", receiver: { kind: "path", path: "state" }, name: "0" },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /item\.as_ref\(\)\.map\(\|__tsonic_optional_receiver\| \{/u);
});

test("long multi-supertrait headers use rustfmt-compatible vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_CompleteProjectObject",
      visibility: "private",
      superTraits: [
        { kind: "named", path: "__TsonicDispatch_TaggedProjectObject" },
        { kind: "named", path: "__TsonicDispatch_CountedProjectObject" },
      ],
      functions: [],
    }],
  });

  assert.match(
    source,
    /trait __TsonicDispatch_CompleteProjectObject:\n    __TsonicDispatch_TaggedProjectObject \+ __TsonicDispatch_CountedProjectObject\n\{\n\}/u,
  );
});

test("string concatenation preserves vertical chains inside trailing blocks", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "append",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "string-concat",
            parts: [
              { kind: "path", path: "current" },
              {
                kind: "block",
                bindings: [{
                  name: "receiver_with_a_deliberately_long_name",
                  value: { kind: "path", path: "value" },
                }],
                value: {
                  kind: "method-call",
                  receiver: {
                    kind: "method-call",
                    receiver: {
                      kind: "field",
                      receiver: { kind: "path", path: "receiver_with_a_deliberately_long_name" },
                      name: "__tsonic_state_with_a_deliberately_long_name",
                    },
                    method: "load_the_complete_project_state_without_inference",
                    args: [],
                  },
                  method: "clone_the_exact_selected_value",
                  args: [],
                },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /format!\("\{\}\{\}", current, \{/u);
  assert.match(
    source,
    /receiver_with_a_deliberately_long_name\n            \.__tsonic_state_with_a_deliberately_long_name\n            \.load_the_complete_project_state_without_inference\(\)\n            \.clone_the_exact_selected_value\(\)/u,
  );
});
