import { test } from "node:test";
import assert from "node:assert/strict";
import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("multiline method-chain arguments use rustfmt-compatible outer-call layout", () => {
  const chain = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: {
        kind: "method-call",
        receiver: { kind: "path", path: "values" },
        method: "get",
        args: [{
          kind: "try",
          expr: {
            kind: "call",
            path: "tsonic_rust_runtime::conversions::i32_to_usize",
            args: [{ kind: "int-literal", text: "1" }],
          },
        }],
      },
      method: "copied",
      args: [],
    },
    method: "is_none",
    args: [],
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      pub: true,
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: { kind: "call", path: "acme_testing::check", args: [chain] },
        }],
      },
    }],
  });

  assert.match(text, /acme_testing::check\(\n        values\n            \.get/u);
  assert.match(text, /            \.is_none\(\),\n    \);/u);
});

test("fitted multi-argument calls stay horizontal inside assignments", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      pub: true,
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "manifest" },
          operator: "=",
          value: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_node::fs::read_file_sync_string",
              args: [
                { kind: "str-literal", value: "Cargo.toml" },
                { kind: "str-literal", value: "utf8" },
              ],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /manifest = tsonic_rust_node::fs::read_file_sync_string\("Cargo.toml", "utf8"\)\?;/u);
});
