import { test } from "node:test";
import assert from "node:assert/strict";
import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("multiline method-chain arguments use rustfmt-compatible outer-call layout", () => {
  const chain = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: {
        kind: "method-call",
        receiver: { kind: "path", path: "values" },
        method: "get",
        args: [{
          kind: "try",
          expr: {
            kind: "call",
            path: "tsonic_rust_runtime::conversions::i32_to_usize",
            args: [{ kind: "int-literal", text: "1" }],
          },
        }],
      },
      method: "copied",
      args: [],
    },
    method: "is_none",
    args: [],
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: { kind: "call", path: "acme_testing::check", args: [chain] },
        }],
      },
    }],
  });

  assert.match(text, /acme_testing::check\(\n        values\n            \.get\(tsonic_rust_runtime::conversions::i32_to_usize\(1\)\?\)\n            \.copied\(\)\n            \.is_none\(\),\n    \);/u);
});

test("fitted multi-argument calls stay horizontal inside assignments", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "manifest" },
          operator: "=",
          value: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_node::fs::read_file_sync_string",
              args: [
                { kind: "str-literal", value: "Cargo.toml" },
                { kind: "str-literal", value: "utf8" },
              ],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /manifest = tsonic_rust_node::fs::read_file_sync_string\("Cargo.toml", "utf8"\)\?;/u);
});

test("a fitted outer call stays attached to its multiline nested call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "call",
                path: "tsonic_rust_js::string::js_len",
                args: [{
                  kind: "reference",
                  expr: {
                    kind: "call",
                    path: "tsonic_rust_node::os::platform_with_a_deliberately_long_name",
                    args: [],
                  },
                }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /usize_to_i32\(tsonic_rust_js::string::js_len\(\n        &tsonic_rust_node/u);
  assert.doesNotMatch(text, /usize_to_i32\(\n        tsonic_rust_js/u);
});

test("a nested call owns the fitting break inside a wider expression", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: ">",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::usize_to_i32",
                  args: [{
                    kind: "call",
                    path: "js_string::js_len",
                    args: [{
                      kind: "reference",
                      expr: {
                        kind: "call",
                        path: "tsonic_rust_node::os::platform",
                        args: [],
                      },
                    }],
                  }],
                },
              },
              right: { kind: "int-literal", text: "0" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /usize_to_i32\(js_string::js_len\(\n            &tsonic_rust_node::os::platform\(\),\n        \)\)\? > 0/u);
});

test("a fallible nested call owns the fitting break", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "bool-literal", value: true },
          then: {
            statements: [{
              kind: "expr",
              expr: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_node::crypto::random_bytes",
                  args: [{
                    kind: "try",
                    expr: {
                      kind: "call",
                      path: "tsonic_rust_runtime::conversions::i32_to_usize",
                      args: [{ kind: "int-literal", text: "16" }],
                    },
                  }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /random_bytes\(tsonic_rust_runtime::conversions::i32_to_usize\(\n            16,\n        \)\?\)\?/u);
});

test("a long outer call expands before a jointly fitting method argument", () => {
  const clone = (name) => ({
    kind: "method-call",
    receiver: { kind: "path", path: name },
    method: "clone",
    args: [],
  });
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "method-call",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "values" },
                  method: "load",
                  args: [],
                },
                method: "push",
                args: [{
                  kind: "try",
                  expr: {
                    kind: "call",
                    path: "nextValue",
                    args: [clone("alias"), clone("calls")],
                  },
                }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /usize_to_i32\(\n        values\.load\(\)\.push\(nextValue\(alias\.clone\(\), calls\.clone\(\)\)\?\),\n    \)\?;/u);
});

test("an outer call stays attached to an expanded associated call", () => {
  const optionalLocation = (name) => ({
    kind: "method-call",
    receiver: {
      kind: "call",
      path: "Some",
      args: [{
        kind: "method-call",
        receiver: { kind: "path", path: name },
        method: "clone",
        args: [],
      }],
    },
    method: "as_ref",
    args: [],
  });
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Location",
                typeArguments: [{ kind: "primitive", name: "i32" }],
              },
              method: "same",
              args: [optionalLocation("first"), optionalLocation("firstAgain")],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(rt::Location::<i32>::same\(\n        Some\(first\.clone\(\)\)\.as_ref\(\),\n        Some\(firstAgain\.clone\(\)\)\.as_ref\(\),\n    \)\);/u);
});

test("a single block argument stays attached to its outer call", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "run",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
          kind: "call",
          path: "conversion_with_an_intentionally_long_name",
          args: [{
            kind: "block",
            bindings: [{
              name: "location",
              value: { kind: "call", path: "load_location", args: [] },
            }],
            value: {
              kind: "method-call",
              receiver: { kind: "path", path: "location" },
              method: "with_mut",
              args: [{
                kind: "closure",
                params: [{ name: "value", byRefCopy: false }],
                body: { kind: "path", path: "value" },
              }],
            },
          }],
          },
        }],
      },
    }],
  });

  assert.match(source, /conversion_with_an_intentionally_long_name\(\{\n/);
  assert.match(source, /\n    \}\);/);
});

test("a trailing fitted closure stays attached after preceding arguments", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "run",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "total",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "reduce_with_array",
            args: [
              { kind: "int-literal", text: "0" },
              {
                kind: "closure",
                params: [
                  { name: "sum", byRefCopy: false },
                  { name: "value", byRefCopy: false },
                  { name: "current", byRefCopy: false },
                  { name: "array", byRefCopy: false },
                ],
                body: {
                  kind: "conditional",
                  condition: {
                    kind: "binary",
                    operator: ">=",
                    left: { kind: "path", path: "current" },
                    right: { kind: "float-literal", text: "0.0" },
                  },
                  whenTrue: {
                    kind: "binary",
                    operator: "+",
                    left: { kind: "path", path: "sum" },
                    right: { kind: "path", path: "value" },
                  },
                  whenFalse: { kind: "path", path: "sum" },
                },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /let total = values\.reduce_with_array\(0, \|sum, value, current, array\| \{\n/u);
  assert.match(source, /\n    \}\);/u);
  assert.doesNotMatch(source, /reduce_with_array\(\n/u);
});

test("three-field struct literals use rustfmt-compatible vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "new_item",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "struct-literal",
            path: "TodoItem",
            fields: [
              { name: "id", value: { kind: "path", path: "id" } },
              { name: "title", value: { kind: "path", path: "title" } },
              { name: "completed", value: { kind: "bool-literal", value: false } },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /TodoItem \{\n        id,\n        title,\n        completed: false,\n    \}/u);
});

test("a fitted condition moves only its overflowing brace", () => {
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "||",
      left: {
        kind: "binary",
        operator: "!=",
        left: { kind: "call", path: "js_abi::math_pow", args: [{ kind: "float-literal", text: "2.0" }, { kind: "float-literal", text: "10.0" }] },
        right: { kind: "float-literal", text: "1024.0" },
      },
      right: {
        kind: "binary",
        operator: "!=",
        left: { kind: "call", path: "absolute_value", args: [{ kind: "float-literal", text: "-5.0" }] },
        right: { kind: "float-literal", text: "5.0" },
      },
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: { kind: "call", path: "truncate_value", args: [{ kind: "float-literal", text: "-2.7" }] },
      right: { kind: "float-literal", text: "-2.0" },
    },
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(source, /truncate_value\(-2\.7\) != -2\.0\n    \{\}/u);
});

test("comparisons follow multiline arithmetic operands", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: {
            kind: "binary",
            operator: "!=",
            left: {
              kind: "binary",
              operator: "+",
              left: { kind: "call", path: "first_source_value_with_a_deliberately_long_name", args: [] },
              right: { kind: "call", path: "second_source_value_with_a_deliberately_long_name", args: [] },
            },
            right: { kind: "int-literal", text: "7" },
          },
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(source, /first_source_value_with_a_deliberately_long_name\(\)\n        \+ second_source_value_with_a_deliberately_long_name\(\)\n        != 7/u);
});

test("long let-bound method chains stay attached to their receiver", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "module_value_with_a_deliberately_long_generated_identity",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: { kind: "path", path: "second" },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "module_binding", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "module_binding" },
                  method: "location",
                  args: [],
                },
              }],
            },
            method: "clone",
            args: [],
          },
        }],
      },
    }],
  });

  assert.match(source, /let module_value_with_a_deliberately_long_generated_identity = second\n        \.with\(\|module_binding\| module_binding\.location\(\)\)\n        \.clone\(\);/u);
});

test("one-field struct literals honor rustfmt's compact body limit", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "new_counter",
      params: [],
      body: {
        statements: [
          {
            kind: "let",
            name: "simple",
            mutable: false,
            init: {
              kind: "struct-literal",
              path: "Counter",
              fields: [{ name: "value", value: { kind: "int-literal", text: "1" } }],
            },
          },
          {
            kind: "tail",
            expr: {
              kind: "struct-literal",
              path: "Counter",
              fields: [{
                name: "value",
                value: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "value" },
                  method: "clone",
                  args: [],
                },
              }],
            },
          },
        ],
      },
    }],
  });

  assert.match(source, /let simple = Counter \{ value: 1 \};/u);
  assert.match(source, /Counter \{\n        value: value\.clone\(\),\n    \}/u);
});

test("typed bindings retain overflowing struct openings and expand their fields", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "new_pair",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "pair",
          mutable: false,
          type: { kind: "named", path: "Pair", typeArguments: [{ kind: "named", path: "i32" }] },
          init: {
            kind: "struct-literal",
            path: "Pair",
            fields: [{
              name: "__tsonic_state",
              value: {
                kind: "call",
                path: "rt::ObjectHandle::new",
                args: [{
                  kind: "tuple-literal",
                  elements: [
                    { kind: "int-literal", text: "1" },
                    { kind: "call", path: "String::from", args: [{ kind: "str-literal", value: "kept" }] },
                    { kind: "int-literal", text: "2" },
                  ],
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /let pair: Pair<i32> = Pair \{\n        __tsonic_state: rt::ObjectHandle::new/u);
});

test("optional closure chains and nested struct arguments stay rustfmt-stable", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [
          {
            kind: "expr",
            expr: {
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "value" },
                method: "as_ref",
                args: [],
              },
              method: "map",
              args: [{
                kind: "closure",
                params: [{ name: "selected", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "selected" },
                  method: "operation_with_a_deliberately_long_name_that_requires_a_closure_body_break",
                  args: [],
                },
              }],
            },
          },
          {
            kind: "expr",
            expr: {
              kind: "call",
              path: "read",
              args: [{
                kind: "call",
                path: "Some",
                args: [{
                  kind: "struct-literal",
                  path: "Box",
                  fields: [{
                    name: "state",
                    value: {
                      kind: "call",
                      path: "ObjectHandle::new",
                      args: [{ kind: "int-literal", text: "7" }],
                    },
                  }],
                }],
              }],
            },
          },
          {
            kind: "expr",
            expr: {
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "read",
                  args: [{
                    kind: "call",
                    path: "Some",
                    args: [{
                      kind: "struct-literal",
                      path: "Box",
                      fields: [{
                        name: "state",
                        value: {
                          kind: "call",
                          path: "ObjectHandle::new",
                          args: [{ kind: "int-literal", text: "7" }],
                        },
                      }],
                    }],
                  }],
                },
                method: "unwrap_or",
                args: [{ kind: "unary", operator: "-", operand: { kind: "int-literal", text: "1" } }],
              },
              right: { kind: "int-literal", text: "7" },
            },
          },
        ],
      },
    }],
  });

  assert.match(source, /value\.as_ref\(\)\.map\(\|selected\| \{\n/u);
  assert.match(source, /read\(Some\(Box \{\n        state: ObjectHandle::new\(7\),\n    \}\)\);/u);
  assert.match(source, /read\(Some\(Box \{\n        state: ObjectHandle::new\(7\),\n    \}\)\)\n    \.unwrap_or\(-1\)\n        == 7;/u);
});

test("long logical chains use rustfmt-compatible operand-per-line layout", () => {
  const terms = Array.from({ length: 7 }, (_, index) => ({
    kind: "binary",
    operator: "!=",
    left: { kind: "call", path: "fibonacci", args: [{ kind: "int-literal", text: String(index) }] },
    right: { kind: "int-literal", text: String(index) },
  }));
  const condition = terms.slice(1).reduce(
    (left, right) => ({ kind: "binary", operator: "||", left, right }),
    terms[0],
  );
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition,
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(text, /if fibonacci\(0\) != 0\n        \|\| fibonacci\(1\) != 1\n        \|\| fibonacci\(2\) != 2/u);
});

test("multiline mixed logical groups preserve source precedence", () => {
  const call = (suffix) => ({
    kind: "call",
    path: `predicate_with_an_intentionally_long_name_${suffix}`,
    args: [{ kind: "path", path: "value" }],
  });
  const condition = {
    kind: "binary",
    operator: "&&",
    left: { kind: "path", path: "enabled" },
    right: {
      kind: "binary",
      operator: "||",
      left: call("left"),
      right: call("right"),
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition,
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(text, /enabled\n        && \(predicate_with_an_intentionally_long_name_left\(value\)\n            \|\| predicate_with_an_intentionally_long_name_right\(value\)\)/u);
});

test("statement-valued expressions are parenthesized as binary operands", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      returnType: { kind: "primitive", name: "i32" },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "binary",
            operator: "+",
            left: {
              kind: "block",
              bindings: [{
                name: "selected",
                value: { kind: "int-literal", text: "1" },
              }],
              value: { kind: "path", path: "selected" },
            },
            right: { kind: "int-literal", text: "1" },
          },
        }],
      },
    }],
  });

  assert.match(text, /\(\{\n        let selected = 1;\n        selected\n    \}\) \+ 1/u);
});

test("long assignments break after the assignment operator", () => {
  const conversion = {
    kind: "call",
    path: "tsonic_rust_runtime::conversions::i32_to_usize",
    args: [{ kind: "int-literal", text: "0" }],
  };
  const element = {
    kind: "index",
    receiver: { kind: "path", path: "values" },
    index: { kind: "try", expr: conversion },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: element,
          operator: "=",
          value: {
            kind: "binary",
            operator: "+",
            left: element,
            right: { kind: "int-literal", text: "1" },
          },
        }],
      },
    }],
  });

  assert.match(text, /values\[tsonic_rust_runtime::conversions::i32_to_usize\(0\)\?\] =\n        values\[/u);
});

test("multiline arithmetic assignments break after the assignment operator", () => {
  const value = {
    kind: "binary",
    operator: "+",
    left: {
      kind: "try",
      expr: {
        kind: "call",
        path: "tsonic_rust_runtime::conversions::usize_to_i32",
        args: [{
          kind: "call",
          path: "js_string::js_len",
          args: [{ kind: "reference", expr: { kind: "path", path: "entry.0" } }],
        }],
      },
    },
    right: { kind: "path", path: "entry.1" },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "entryTotal" },
          operator: "+=",
          value,
        }],
      },
    }],
  });

  assert.match(text, /entryTotal \+=\n        tsonic_rust_runtime::conversions::usize_to_i32/u);
});

test("overflowing nested calls retain attached wrappers and jointly fitting arguments", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::isize_to_i32",
              args: [{
                kind: "call",
                path: "example_runtime::canonical_array_index_of",
                args: [
                  { kind: "reference", expr: { kind: "path", path: "values" } },
                  { kind: "reference", expr: { kind: "int-literal", text: "3" } },
                  { kind: "int-literal", text: "0" },
                ],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /isize_to_i32\(example_runtime::canonical_array_index_of\(\n        &values, &3, 0,\n    \)\)\?/u);
});

test("nested calls beyond rustfmt call width put each argument on its own line", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "tsonic_rust_node::url::can_parse",
              args: [
                { kind: "str-literal", value: "https://example.com" },
                { kind: "path", path: "None" },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /can_parse\(\n        "https:\/\/example\.com",\n        None,\n    \)\);/u);
});

test("nested single-argument wrappers stay attached to the expanded inner call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "js_abi::number_is_nan",
              args: [{
                kind: "call",
                path: "js_abi::math_pow",
                args: [
                  { kind: "float-literal", text: "1.0" },
                  { kind: "path", path: "js_abi::NUMBER_POSITIVE_INFINITY" },
                ],
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /check\(js_abi::number_is_nan\(js_abi::math_pow\(\n        1\.0,\n        js_abi::NUMBER_POSITIVE_INFINITY,\n    \)\)\);/u);
});

test("fallible nested calls in comparisons use rustfmt-compatible wrapper layout", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::isize_to_i32",
                  args: [{
                    kind: "call",
                    path: "js_string::last_index_of_from_end",
                    args: [
                      { kind: "str-literal", value: "banana" },
                      { kind: "str-literal", value: "ana" },
                    ],
                  }],
                },
              },
              right: { kind: "int-literal", text: "3" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /isize_to_i32\(js_string::last_index_of_from_end\(\n            "banana", "ana",\n        \)\)\? == 3/u);
});

test("long borrowed slices use rustfmt-compatible element layout", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "node_util::format",
              args: [
                { kind: "str-literal", value: "%s:%d" },
                {
                  kind: "reference",
                  expr: {
                    kind: "slice-literal",
                    elements: [
                      {
                        kind: "call",
                        path: "tsonic_rust_js::abi::JsValue::from",
                        args: [{ kind: "string-literal", value: "count" }],
                      },
                      {
                        kind: "call",
                        path: "tsonic_rust_js::abi::JsValue::from",
                        args: [{ kind: "float-literal", text: "3.0" }],
                      },
                    ],
                  },
                },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /&\[\n            tsonic_rust_js::abi::JsValue::from\(String::from\("count"\)\),\n            tsonic_rust_js::abi::JsValue::from\(3\.0\),\n        \],/u);
});

test("single long borrowed slice arguments stay attached to their call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "js_abi::console_log",
            args: [{
              kind: "reference",
              expr: {
                kind: "slice-literal",
                elements: [
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::js_value_from_string",
                    args: [{ kind: "reference", expr: { kind: "path", path: "label" } }],
                  },
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::JsValue::from",
                    args: [{ kind: "float-literal", text: "6.0" }],
                  },
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::JsValue::from",
                    args: [{ kind: "bool-literal", value: true }],
                  },
                ],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /js_abi::console_log\(&\[\n        tsonic_rust_js::abi::js_value_from_string\(&label\),\n        tsonic_rust_js::abi::JsValue::from\(6\.0\),\n        tsonic_rust_js::abi::JsValue::from\(true\),\n    \]\);/u);
  assert.doesNotMatch(text, /js_abi::console_log\(\n/u);
});

test("single long owned array arguments stay attached to their call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "push_many",
            args: [{
              kind: "slice-literal",
              elements: [
                {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::f64_to_i32",
                  args: [{ kind: "float-literal", text: "2.0" }],
                },
                {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::f64_to_i32",
                  args: [{ kind: "float-literal", text: "3.0" }],
                },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /values\.push_many\(\[\n        tsonic_rust_runtime::conversions::f64_to_i32\(2\.0\),\n        tsonic_rust_runtime::conversions::f64_to_i32\(3\.0\),\n    \]\);/u);
  assert.doesNotMatch(text, /values\.push_many\(\n/u);
});

test("logical assignment keeps a fitting first operand beside the operator", () => {
  const first = {
    kind: "call",
    path: "js_string::includes",
    args: [
      { kind: "reference", expr: { kind: "path", path: "rendered" } },
      { kind: "str-literal", value: "tsonic" },
      { kind: "int-literal", text: "0" },
    ],
  };
  const condition = {
    kind: "binary",
    operator: "&&",
    left: {
      kind: "binary",
      operator: "&&",
      left: first,
      right: { kind: "call", path: "digits.test", args: [{ kind: "str-literal", value: "a12" }] },
    },
    right: {
      kind: "binary",
      operator: "==",
      left: { kind: "path", path: "date_value_with_an_intentionally_long_name_for_rustfmt" },
      right: { kind: "int-literal", text: "1" },
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "passed" },
          operator: "=",
          value: condition,
        }],
      },
    }],
  });

  assert.match(text, /passed = js_string::includes\(&rendered, "tsonic", 0\)\n        && digits\.test/u);
});
