import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

function projectFunction(expression) {
  return printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "tail", expr: expression }] },
    }],
  });
}

function clone(expression) {
  return { kind: "method-call", receiver: expression, method: "clone", args: [] };
}

function field(receiver, name) {
  return { kind: "field", receiver, name };
}

test("nested tuple fields use one edition-neutral rustfmt-stable form", () => {
  const text = projectFunction(field(field(field({ kind: "path", path: "state" }, "0"), "1"), "0"));

  assert.match(text, /\(\(state\.0\)\.1\)\.0/u);
  assert.doesNotMatch(text, /state\.0 \.1|state\.0\.1/u);
});

test("logical block operands keep the following operator on the closing brace", () => {
  const upcast = () => ({
    kind: "block",
    bindings: [{ name: "value", value: clone({ kind: "path", path: "source" }) }],
    value: {
      kind: "struct-literal",
      path: "View",
      fields: [
        { name: "identity", value: clone(field({ kind: "path", path: "value" }, "identity")) },
        { name: "dispatch", value: clone(field({ kind: "path", path: "value" }, "dispatch")) },
      ],
    },
  });
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "!=",
      left: { kind: "path", path: "first" },
      right: upcast(),
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: { kind: "path", path: "second" },
      right: upcast(),
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(text, /\n    \} \|\| second != \{/u);
  assert.doesNotMatch(text, /\n    \}\n        \|\| second/u);
});

test("format macro arguments keep borrowed blocks attached to their call", () => {
  const text = projectFunction({
    kind: "string-concat",
    parts: [
      { kind: "string-literal", value: "base:" },
      {
        kind: "call",
        path: "rt::source_string",
        args: [{
          kind: "reference",
          expr: {
            kind: "block",
            bindings: [{
              name: "receiver",
              value: clone({ kind: "path", path: "project_this" }),
            }],
            value: {
              kind: "method-call",
              receiver: clone(field({ kind: "path", path: "receiver" }, "dispatch")),
              method: "read_selected_project_field_with_a_long_identity",
              args: [],
            },
          },
        }],
      },
      { kind: "string-literal", value: "" },
    ],
  });

  assert.match(text, /rt::source_string\(&\{\n            let receiver/u);
  assert.match(text, /\n        \},\),\n/u);
  assert.doesNotMatch(text, /rt::source_string\(\n/u);
});

test("method chains in logical continuations use the continuation body indent", () => {
  const selected = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: { kind: "path", path: "secondLocation" },
      method: "with",
      args: [{
        kind: "closure",
        params: [{ name: "__tsonic_module_binding", byRefCopy: false }],
        body: {
          kind: "method-call",
          receiver: { kind: "path", path: "__tsonic_module_binding" },
          method: "load",
          args: [],
        },
      }],
    },
    method: "load",
    args: [],
  };
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "!=",
      left: { kind: "path", path: "first" },
      right: { kind: "int-literal", text: "3" },
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: selected,
      right: { kind: "int-literal", text: "4" },
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(text, /\n        \|\| secondLocation\n            \.with/u);
  assert.match(text, /\n            \.load\(\)\n            != 4/u);
});
