import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

function projectFunction(expression) {
  return printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "tail", expr: expression }] },
    }],
  });
}

function clone(expression) {
  return { kind: "method-call", receiver: expression, method: "clone", args: [] };
}

function field(receiver, name) {
  return { kind: "field", receiver, name };
}

test("nested tuple fields use one edition-neutral rustfmt-stable form", () => {
  const text = projectFunction(field(field(field({ kind: "path", path: "state" }, "0"), "1"), "0"));

  assert.match(text, /\(\(state\.0\)\.1\)\.0/u);
  assert.doesNotMatch(text, /state\.0 \.1|state\.0\.1/u);
});

test("logical block operands keep the following operator on the closing brace", () => {
  const upcast = () => ({
    kind: "block",
    bindings: [{ name: "value", value: clone({ kind: "path", path: "source" }) }],
    value: {
      kind: "struct-literal",
      path: "View",
      fields: [
        { name: "identity", value: clone(field({ kind: "path", path: "value" }, "identity")) },
        { name: "dispatch", value: clone(field({ kind: "path", path: "value" }, "dispatch")) },
      ],
    },
  });
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "||",
      left: {
        kind: "binary",
        operator: "!=",
        left: { kind: "path", path: "first" },
        right: upcast(),
      },
      right: {
        kind: "binary",
        operator: "!=",
        left: { kind: "path", path: "second" },
        right: upcast(),
      },
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: { kind: "path", path: "third" },
      right: upcast(),
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(text, /\n    \} \|\| second != \{/u);
  assert.match(text, /\n    \} \|\| third != \{/u);
  assert.doesNotMatch(text, /\n            let value/u);
});

test("detached logical block operands use the continuation indentation", () => {
  const selectedValue = (receiver) => ({
    kind: "block",
    bindings: [{ name: "selected", value: clone({ kind: "path", path: receiver }) }],
    value: {
      kind: "method-call",
      receiver: clone(field({ kind: "path", path: "selected" }, "dispatch")),
      method: "read_selected_value",
      args: [],
    },
  });
  const compared = (receiver, value) => ({
    kind: "binary",
    operator: "!=",
    left: selectedValue(receiver),
    right: { kind: "string-literal", value },
  });
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: {
            kind: "binary",
            operator: "||",
            left: compared("first", "one"),
            right: compared("second", "two"),
          },
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(text, /\n        \|\| \{\n            let selected/u);
  assert.match(text, /\n        \} != String::from\("two"\)\n    \{/u);
});

test("format macro arguments keep borrowed blocks attached to their call", () => {
  const text = projectFunction({
    kind: "string-concat",
    parts: [
      { kind: "string-literal", value: "base:" },
      {
        kind: "call",
        path: "rt::source_string",
        args: [{
          kind: "reference",
          expr: {
            kind: "block",
            bindings: [{
              name: "receiver",
              value: clone({ kind: "path", path: "project_this" }),
            }],
            value: {
              kind: "method-call",
              receiver: clone(field({ kind: "path", path: "receiver" }, "dispatch")),
              method: "read_selected_project_field_with_a_long_identity",
              args: [],
            },
          },
        }],
      },
      { kind: "string-literal", value: "" },
    ],
  });

  assert.match(text, /rt::source_string\(&\{\n            let receiver/u);
  assert.match(text, /\n        \},\),\n/u);
  assert.doesNotMatch(text, /rt::source_string\(\n/u);
});

test("format macro arguments keep borrowed nested calls attached to their call", () => {
  const expression = {
    kind: "string-concat",
    parts: [
      { kind: "string-literal", value: "middle>" },
      {
        kind: "call",
        path: "rt::source_string",
        args: [{
          kind: "reference",
          expr: {
            kind: "associated-call",
            owner: { kind: "named", path: "Self" },
            trait: { kind: "named", path: "__TsonicDispatch_Base" },
            method: "__tsonic_exact_489_549",
            args: [clone({ kind: "path", path: "self" })],
          },
        }],
      },
      { kind: "string-literal", value: "" },
    ],
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "impl",
      target: { kind: "named", path: "Proof" },
      functions: [{
        name: "proof",
        visibility: "private",
        selfParam: "rc",
        params: [],
        body: { statements: [{ kind: "tail", expr: expression }] },
      }],
    }],
  });

  assert.match(
    text,
    /rt::source_string\(&<Self as __TsonicDispatch_Base>::__tsonic_exact_489_549\(\n/u,
  );
  assert.match(text, /self\.clone\(\)\n\s+\),\),/u);
  assert.doesNotMatch(text, /rt::source_string\(\n/u);
});

test("multiline awaited match-arm expressions use a canonical arm block", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      isAsync: true,
      fallible: true,
      params: [],
      body: {
        statements: [{
          kind: "try-scope",
          bodyName: "try_body",
          flowName: "try_flow",
          returnType: { kind: "unit" },
          fallible: true,
          asynchronous: true,
          body: {
            statements: [{ kind: "expr", expr: { kind: "call", path: "may_fail", args: [] } }],
          },
          bodyFallible: true,
          bodyTerminates: false,
          catchClause: {
            binding: "_",
            body: {
              statements: [{ kind: "expr", expr: { kind: "call", path: "record_failure", args: [] } }],
            },
            fallible: true,
            terminates: false,
          },
          propagate: false,
          dispatchReturn: false,
          dispatchTargets: [],
          terminates: false,
        }],
      },
    }],
  });

  assert.match(text, /Err\(_\) => \{\n\s+\(async \{/u);
  assert.match(text, /\n\s+\.await\n\s+\}\n/u);
  assert.doesNotMatch(text, /\n\s+\.await\n\s+\},/u);
  assert.doesNotMatch(text, /Err\(_\) => \(async \{/u);
});

test("multiline synchronous match-arm expressions remain direct", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      fallible: true,
      params: [],
      body: {
        statements: [{
          kind: "try-scope",
          bodyName: "try_body",
          flowName: "try_flow",
          returnType: { kind: "unit" },
          fallible: true,
          asynchronous: false,
          body: {
            statements: [{ kind: "expr", expr: { kind: "call", path: "may_fail", args: [] } }],
          },
          bodyFallible: true,
          bodyTerminates: false,
          catchClause: {
            binding: "_",
            body: {
              statements: [{ kind: "expr", expr: { kind: "call", path: "record_failure", args: [] } }],
            },
            fallible: true,
            terminates: false,
          },
          propagate: false,
          dispatchReturn: false,
          dispatchTargets: [],
          terminates: false,
        }],
      },
    }],
  });

  assert.match(text, /Err\(_\) => rt::completion_region\(\|\| \{/u);
  assert.doesNotMatch(text, /Err\(_\) => \{\n\s+rt::completion_region/u);
});

test("method chains in logical continuations use the continuation body indent", () => {
  const selected = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: { kind: "path", path: "secondLocation" },
      method: "with",
      args: [{
        kind: "closure",
        params: [{ name: "__tsonic_module_binding", byRefCopy: false }],
        body: {
          kind: "method-call",
          receiver: { kind: "path", path: "__tsonic_module_binding" },
          method: "load",
          args: [],
        },
      }],
    },
    method: "load",
    args: [],
  };
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "!=",
      left: { kind: "path", path: "first" },
      right: { kind: "int-literal", text: "3" },
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: selected,
      right: { kind: "int-literal", text: "4" },
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(text, /\n        \|\| secondLocation\n            \.with/u);
  assert.match(text, /\n            \.load\(\)\n            != 4/u);
});
