import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../dist/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("rustfmt-stable calls, closures, conditionals, and borrowed fallible chains", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "field_label",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: { kind: "path", path: "label" },
              method: "clone",
              args: [],
            }, {
              kind: "path",
              path: "std::convert::identity",
            }, {
              kind: "closure",
              params: [],
              body: {
                kind: "call",
                path: "String::from",
                args: [{ kind: "str-literal", value: "none" }],
              },
            }],
          },
        }, {
          kind: "let",
          name: "loud",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "conditional",
            condition: { kind: "path", path: "selected" },
            whenTrue: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "READY" }],
            },
            whenFalse: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "SET" }],
            },
          },
        }, {
          kind: "expr",
          expr: {
            kind: "string-concat",
            parts: [{
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }, {
              kind: "call",
              path: "rt::source_string",
              args: [{
                kind: "reference",
                expr: {
                  kind: "try",
                  errorDomain: "runtime",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "callable" },
                    method: "call",
                    args: [{
                      kind: "tuple-literal",
                      elements: [{
                        kind: "try",
                        errorDomain: "runtime",
                        expr: {
                          kind: "call",
                          path: "tsonic_rust_runtime::conversions::f64_to_i32",
                          args: [{ kind: "float-literal", text: "3.0" }],
                        },
                      }, {
                        kind: "call",
                        path: "Some",
                        args: [{
                          kind: "call",
                          path: "String::from",
                          args: [{ kind: "str-literal", value: "bound" }],
                        }],
                      }],
                    }],
                  },
                },
              }],
            }, {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "call_bound",
            args: [{ kind: "path", path: "receiver" }, {
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Callable",
                typeArguments: [{
                  kind: "tuple",
                  elements: [
                    { kind: "primitive", name: "i32" },
                    {
                      kind: "named",
                      path: "Option",
                      typeArguments: [{ kind: "string" }],
                    },
                  ],
                }, {
                  kind: "named",
                  path: "rt::TsonicResult",
                  typeArguments: [{ kind: "string" }],
                }],
              },
              method: "new",
              args: [{
                kind: "closure-block",
                params: [{ name: "callable_arguments", mutable: false }],
                move: true,
                async: false,
                body: {
                  statements: [{
                    kind: "tail",
                    expr: {
                      kind: "call",
                      path: "Ok::<_, rt::TsonicError>",
                      args: [{ kind: "path", path: "callable_arguments.1" }],
                    },
                  }],
                },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let field_label: String =\n {8}rt::option_coalesce\(label\.clone\(\), std::convert::identity, \|\| \{\n {12}String::from\("none"\)\n {8}\}\);/u,
  );
  assert.match(
    source,
    /let loud: String = if selected \{\n {8}String::from\("READY"\)\n {4}\} else \{\n {8}String::from\("SET"\)\n {4}\};/u,
  );
  assert.match(source, /rt::source_string\(&callable\.call\(\(\n/u);
  assert.doesNotMatch(source, /rt::source_string\(&callable\n {8}\.call/u);
  assert.match(
    source,
    /rt::Callable::<\(i32, Option<String>\), rt::TsonicResult<String>>::new\(/u,
  );
  assert.doesNotMatch(source, /rt::Callable::<\n/u);
});
