import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compileRustTarget } from "../../../dist/backend/compile.js";
import { composeRustProviderSemantics } from "../../../dist/providers/packages/semantics.js";
import {
  createRustTargetConfigurationInput,
  sealRustTargetConfiguration,
} from "../../../dist/options/rust-target-options.js";
import {
  planCargoManifest as planSealedCargoManifest,
  planRustCargoProject,
} from "../../../dist/backend/planner/project/cargo.js";
import {
  analyzeRustRuntimeReferences,
} from "../../../dist/analysis/runtime/index.js";
import { printCargoManifest } from "../../../dist/print/project/manifest.js";
import {
  fakeCompileInput,
  fakeSourceFile,
} from "../../helpers/fake-compile-input.mjs";
import { expectedAuthoredRustSource } from "../../helpers/generated-rust-source.mjs";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const runtimeCrate = resolve(repositoryRoot, "../rust-runtime/crates/tsonic_rust_runtime");
const jsCrate = resolve(repositoryRoot, "../rust-js/crates/tsonic_rust_js");
const fixtureRoot = resolve(repositoryRoot, ".temp/cargo-project-fixtures");

function materializedCrate(name, identity = name) {
  const root = resolve(fixtureRoot, identity);
  mkdirSync(resolve(root, "src"), { recursive: true });
  writeFileSync(resolve(root, "Cargo.toml"), [
    "[package]",
    `name = "${name}"`,
    'version = "0.1.0"',
    'edition = "2021"',
    "",
  ].join("\n"));
  writeFileSync(resolve(root, "src/lib.rs"), "pub fn fixture() {}\n");
  return root;
}

const providerSemantics = composeRustProviderSemantics([]);
const generatedConfiguration = Object.freeze({
  crateName: "tsonic_generated",
  edition: "2021",
  outputType: "lib",
  project: Object.freeze({ kind: "generated" }),
});
const noRuntimeReferences = Object.freeze({
  cargoDependencies: Object.freeze([]),
  activeCrates: Object.freeze([]),
});

function planCargoManifest(configuration, runtimeReferences) {
  const analysis = analyzeRustRuntimeReferences(runtimeReferences);
  return analysis.kind === "rejected"
    ? { manifest: undefined, diagnostics: analysis.diagnostics }
    : {
        manifest: planSealedCargoManifest(configuration, analysis.plan),
        diagnostics: [],
      };
}

function compile(input) {
  const configurationInput = createRustTargetConfigurationInput(
    input.target,
    dirname(input.paths.projectFilePath),
    input.paths.targetOutputRoot,
  );
  const configuration = sealRustTargetConfiguration(configurationInput, Object.freeze({
    edition: configurationInput.edition,
    compilerIdentity: "cargo-project-test-harness",
    enabledLanguageFeatures: Object.freeze([]),
  }));
  const result = compileRustTarget(Object.freeze({
    input,
    configuration,
    providerSemantics,
    jsEnabled: false,
    rootPublishesLibrary: configuration.outputType === "lib",
  }));
  return {
    artifacts: result.kind === "resolved" ? result.value.artifacts : [],
    diagnostics: result.diagnostics,
  };
}

function runtimeReference(crate, path, { registryPatch } = {}) {
  return {
    kind: "cargo-path",
    include: path,
    attributes: { crate, ...(registryPatch === undefined ? {} : { registryPatch }) },
  };
}

test("empty program emits a deterministic cargo library project", () => {
  const result = compile(fakeCompileInput({
    sourceFiles: [fakeSourceFile({ fileName: "src/empty.ts", text: "", statements: [] })],
    runtimeReferences: [runtimeReference(
      "tsonic_rust_runtime",
      runtimeCrate,
      { registryPatch: "crates-io" },
    )],
  }));

  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.artifacts.map((artifact) => [artifact.kind, artifact.path]), [
    ["project", "Cargo.toml"],
    ["source", "src/lib.rs"],
    ["source", "src/empty.rs"],
  ]);
  const manifest = result.artifacts[0].text;
  assert.equal(manifest, [
    "[package]",
    'name = "tsonic_generated"',
    'version = "0.1.0"',
    'edition = "2021"',
    "",
    "[workspace]",
    'resolver = "3"',
    "",
    "[dependencies]",
    `tsonic_rust_runtime = { path = "${runtimeCrate}" }`,
    "",
    "[patch.crates-io]",
    `tsonic_rust_runtime = { path = "${runtimeCrate}" }`,
    "",
  ].join("\n"));
  const librarySource = result.artifacts[1];
  assert.equal(librarySource.language, "rust");
  assert.equal(librarySource.text, [
    "// Generated by the Tsonic Rust target. Do not edit.",
    "",
    "#[doc(hidden)]",
    "pub mod empty;",
    "",
  ].join("\n"));
  assert.equal(result.artifacts[2].text, expectedAuthoredRustSource());
});

test("bin output without an exported entry main fails closed", () => {
  const result = compile(fakeCompileInput({
    target: { id: "rust", options: { outputType: "bin", crateName: "my_app", edition: "2024" } },
    runtimeReferences: [runtimeReference(
      "tsonic_rust_runtime",
      runtimeCrate,
      { registryPatch: "crates-io" },
    )],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.ok(result.diagnostics.some((diagnostic) => diagnostic.code === "RUST_MISSING_ENTRYPOINT"));
});

test("cargo dependencies are sorted and deduplicated deterministically", () => {
  const plan = planCargoManifest(generatedConfiguration, [
    runtimeReference("tsonic_rust_runtime", runtimeCrate),
    runtimeReference("tsonic_rust_js", jsCrate),
    runtimeReference("tsonic_rust_runtime", runtimeCrate),
  ]);

  assert.deepEqual(plan.diagnostics, []);
  assert.deepEqual(plan.manifest.dependencies.map((dependency) => dependency.name), [
    "tsonic_rust_js",
    "tsonic_rust_runtime",
  ]);
});

test("unknown runtime reference kinds fail closed without artifacts", () => {
  const result = compile(fakeCompileInput({
    runtimeReferences: [{ kind: "project", include: "/repos/x/x.csproj" }],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "RUST_UNSUPPORTED_RUNTIME_REFERENCE");
});

test("only explicit registry-source replacements become Cargo patches", () => {
  const acmeProvider = materializedCrate("acme_provider");
  const plan = planCargoManifest(generatedConfiguration, [
    runtimeReference("acme_provider", acmeProvider),
    runtimeReference("tsonic_rust_runtime", runtimeCrate, {
      registryPatch: "crates-io",
    }),
  ]);
  assert.deepEqual(plan.diagnostics, []);
  const text = printCargoManifest(plan.manifest);

  assert.match(text, new RegExp(`\\[dependencies\\][\\s\\S]*acme_provider = \\{ path = "${acmeProvider}" \\}`, "u"));
  assert.match(text, new RegExp(`\\[patch\\.crates-io\\]\\ntsonic_rust_runtime = \\{ path = "${runtimeCrate}" \\}`, "u"));
  assert.doesNotMatch(text, /\[patch\.crates-io\][\s\S]*acme_provider =/u);
});

test("unknown and conflicting registry patch contracts fail closed", () => {
  const unknown = planCargoManifest(generatedConfiguration, [
    runtimeReference("tsonic_rust_runtime", runtimeCrate, { registryPatch: "private-registry" }),
  ]);
  assert.equal(unknown.manifest, undefined);
  assert.equal(unknown.diagnostics.length, 1);

  const conflicting = planCargoManifest(generatedConfiguration, [
    runtimeReference("tsonic_rust_runtime", runtimeCrate),
    runtimeReference("tsonic_rust_runtime", runtimeCrate, { registryPatch: "crates-io" }),
  ]);
  assert.equal(conflicting.manifest, undefined);
  assert.equal(conflicting.diagnostics.length, 1);
});

test("conflicting crate paths for the same crate name fail closed", () => {
  const first = materializedCrate("conflicting_runtime", "conflicting-runtime-a");
  const second = materializedCrate("conflicting_runtime", "conflicting-runtime-b");
  const plan = planCargoManifest(generatedConfiguration, [
    runtimeReference("conflicting_runtime", first),
    runtimeReference("conflicting_runtime", second),
  ]);

  assert.equal(plan.manifest, undefined);
  assert.equal(plan.diagnostics.length, 1);
});

test("toml strings escape quotes and backslashes", () => {
  const text = printCargoManifest({
    packageName: "tsonic_generated",
    edition: "2021",
    outputType: "lib",
    dependencies: [{ name: "dep", path: 'C:\\repos\\"odd"' }],
  });

  assert.match(text, /dep = \{ path = "C:\\\\repos\\\\\\"odd\\"" \}/);
  assert.equal(text.match(/dep = \{ path = /gu)?.length, 1);
  assert.doesNotMatch(text, /\[patch\.crates-io\]/u);
});

test("toml strings escape every forbidden control character", () => {
  const text = printCargoManifest({
    packageName: "tsonic_generated",
    edition: "2021",
    outputType: "lib",
    dependencies: [{ name: "dep", path: "line\ncol\ttab\rreturn\bback\fform\u0000nul\u001funit\u007fdel" }],
  });

  assert.match(text, /path = "line\\ncol\\ttab\\rreturn\\bback\\fform\\u0000nul\\u001funit\\u007fdel"/u);
  const dependencyLine = text.split("\n").find((line) => line.startsWith("dep = "));
  assert.ok(dependencyLine);
  assert.doesNotMatch(dependencyLine, /[\u0000-\u001f\u007f]/u);
});

test("Cargo path references require exact materialized crate identity", () => {
  const wrongIdentity = materializedCrate("actual_crate", "wrong-identity");
  const missing = resolve(fixtureRoot, "missing-crate");
  const malformed = resolve(fixtureRoot, "malformed-crate");
  mkdirSync(malformed, { recursive: true });
  writeFileSync(resolve(malformed, "Cargo.toml"), "[package]\nname.workspace = true\n");

  for (const [reference, expectedMessage] of [
    [runtimeReference("declared_crate", wrongIdentity), /conflicts with Cargo package 'actual_crate'/u],
    [runtimeReference("missing_crate", missing), /crate directory cannot be read/u],
    [runtimeReference("malformed_crate", malformed), /must declare one direct literal/u],
    [runtimeReference("bad-name", wrongIdentity), /not a valid Rust crate identifier/u],
    [{ ...runtimeReference("actual_crate", wrongIdentity), attributes: { crate: "actual_crate", guess: "yes" } }, /attribute 'guess'/u],
    [runtimeReference("actual_crate", `${wrongIdentity}/../wrong-identity`), /absolute normalized path/u],
  ]) {
    const plan = planCargoManifest(generatedConfiguration, [reference]);
    assert.equal(plan.manifest, undefined);
    assert.equal(plan.diagnostics.length, 1);
    assert.equal(plan.diagnostics[0].code, "RUST_INVALID_CARGO_REFERENCE");
    assert.match(plan.diagnostics[0].message, expectedMessage);
  }
});

test("sparse Cargo runtime-reference lists fail closed", () => {
  const references = new Array(2);
  references[1] = runtimeReference("tsonic_rust_runtime", runtimeCrate);
  const plan = planCargoManifest(generatedConfiguration, references);

  assert.equal(plan.manifest, undefined);
  assert.equal(plan.diagnostics.length, 1);
  assert.match(plan.diagnostics[0].message, /sparse slot at index 0/u);
});

test("user-owned Cargo mode emits sources without creating or mutating the manifest", () => {
  const root = resolve(fixtureRoot, "user-owned-project");
  const manifestPath = resolve(root, "Cargo.toml");
  mkdirSync(root, { recursive: true });
  const manifestText = "[package]\nname = \"user-owned\"\nversion = \"0.1.0\"\nedition = \"2021\"\n";
  writeFileSync(manifestPath, manifestText);
  const paths = {
    projectFilePath: resolve(repositoryRoot, "tsonic.json"),
    projectRoot: repositoryRoot,
    outputRoot: resolve(repositoryRoot, "out"),
    targetOutputRoot: resolve(repositoryRoot, "out/rust"),
  };

  const configuration = createRustTargetConfigurationInput(
    { id: "rust", options: { projectFile: manifestPath } },
    dirname(paths.projectFilePath),
    paths.targetOutputRoot,
  );
  const plan = planRustCargoProject(configuration, noRuntimeReferences);
  assert.deepEqual(plan, {
    kind: "user-owned",
    manifestPath,
  });
  assert.equal(readFileSync(manifestPath, "utf8"), manifestText);
});

test("user-owned Cargo mode rejects missing, non-Cargo, and generated-output manifests", () => {
  const paths = {
    projectFilePath: resolve(repositoryRoot, "tsonic.json"),
    projectRoot: repositoryRoot,
    outputRoot: resolve(fixtureRoot, "user-owned-output"),
    targetOutputRoot: resolve(fixtureRoot, "user-owned-output/rust"),
  };
  mkdirSync(paths.targetOutputRoot, { recursive: true });
  const insideOutput = resolve(paths.targetOutputRoot, "Cargo.toml");
  const wrongName = resolve(fixtureRoot, "user-owned-project/not-cargo.toml");
  writeFileSync(insideOutput, "[package]\nname = \"bad\"\nversion = \"0.1.0\"\n");
  writeFileSync(wrongName, "[package]\nname = \"bad\"\nversion = \"0.1.0\"\n");

  for (const [configured, expected] of [
    [resolve(fixtureRoot, "missing/Cargo.toml"), /does not exist/u],
    [wrongName, /must point to Cargo\.toml/u],
    [insideOutput, /must not point inside generated target output root/u],
  ]) {
    assert.throws(
      () => createRustTargetConfigurationInput(
        { id: "rust", options: { projectFile: configured } },
        dirname(paths.projectFilePath),
        paths.targetOutputRoot,
      ),
      expected,
    );
  }
});
