import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("fallible tuple call arguments use rustfmt-compatible element layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "invoke",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "formatter" },
            method: "call",
            args: [{
              kind: "tuple-literal",
              elements: [{
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::f64_to_i32",
                  args: [{ kind: "float-literal", text: "3.0" }],
                },
              }, {
                kind: "call",
                path: "String::from",
                args: [{ kind: "str-literal", value: "items" }],
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /formatter\.call\(\(\n {8}tsonic_rust_runtime::conversions::f64_to_i32\(3\.0\)\?,\n {8}String::from\("items"\),\n {4}\)\)/u,
  );
});

test("short fallible tuple call arguments remain on one rustfmt line", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "invoke",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "structural_method_5" },
            method: "call",
            args: [{
              kind: "tuple-literal",
              elements: [{
                kind: "method-call",
                receiver: { kind: "path", path: "method_receiver_5" },
                method: "clone",
                args: [],
              }, {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "argument" },
                  method: "call",
                  args: [{ kind: "path", path: "()" }],
                },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /structural_method_5\.call\(\(method_receiver_5\.clone\(\), argument\.call\(\(\)\)\?\)\)/u,
  );
});

test("long nested callable construction gives the outer call its own break", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "invoke",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "call_detached_format",
            args: [{
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Callable",
                typeArguments: [{
                  kind: "tuple",
                  elements: [
                    { kind: "primitive", name: "i32" },
                    { kind: "named", path: "String" },
                  ],
                }, {
                  kind: "named",
                  path: "rt::TsonicResult<String>",
                }],
              },
              method: "new",
              args: [{
                kind: "closure",
                params: [{ name: "callable_arguments", byRefCopy: false }],
                body: { kind: "path", path: "callable_arguments.1" },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /call_detached_format\(\n {8}rt::Callable::<\(i32, String\), rt::TsonicResult<String>>::new\(/u,
  );
});

test("long outer callable construction keeps block callbacks attached", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "invoke",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "tsonic_rust_node::timers::set_timeout_callable",
            args: [{
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Callable",
                typeArguments: [
                  { kind: "unit" },
                  { kind: "named", path: "rt::TsonicResult<()>" },
                ],
              },
              method: "new",
              args: [{
                kind: "closure-block",
                params: [{ name: "_callable_arguments", byRefCopy: false }],
                body: {
                  statements: [{
                    kind: "tail",
                    expr: {
                      kind: "call",
                      path: "Ok::<_, rt::TsonicError>",
                      args: [{ kind: "path", path: "()" }],
                    },
                  }],
                },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /set_timeout_callable\(rt::Callable::<\(\), rt::TsonicResult<\(\)>>::new\(\n {8}\|_callable_arguments\| \{/u,
  );
});
