import { test } from "node:test";
import assert from "node:assert/strict";
import { emptyRustGenerics } from "../../../dist/backend/target-ast/nodes.js";
import { printRustSourceFile as printFinalRustSourceFile } from "../../helpers/printed-rust-source.mjs";
import { finalizeRustSourceStyle } from "../../../dist/backend/target-ast/normalization/source-style.js";
import { rustLintAttributes } from "../../../dist/backend/target-ast/normalization/lint-policy.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("constant-folded parameter reads retain only the exact unused-binding expectation", () => {
  const parameter = { name: "value", type: { kind: "primitive", name: "bool" } };
  for (const used of [false, true]) {
    const callable = { name: "selected", visibility: "crate", generics: emptyRustGenerics,
      params: [parameter], returnType: parameter.type, body: { statements: [{ kind: "tail",
        expr: used ? { kind: "path", path: "value" } : { kind: "bool-literal", value: true } }] } };
    const model = finalizeRustSourceStyle({ headerComment, items: [
      { ...callable, kind: "function" },
      { kind: "impl", target: { kind: "named", path: "Owner" }, generics: emptyRustGenerics,
        functions: [callable] },
      { kind: "trait", name: "Contract", visibility: "crate", generics: emptyRustGenerics,
        functions: [callable, { ...callable, name: "required", body: undefined }] },
    ] });
    const functions = [model.items[0], model.items[1].functions[0], model.items[2].functions[0]];
    for (const selected of functions) {
      assert.deepEqual(selected.attrs ?? [], used ? [] : [rustLintAttributes.unusedVariables]);
      assert.deepEqual(selected.params, [parameter]);
    }
    assert.deepEqual(model.items[2].functions[1].attrs ?? [], []);
    assert.deepEqual(finalizeRustSourceStyle(model), model);
  }
});

test("only native-unused generic parameters retain a focused contract expectation", () => {
  const parameter = { kind: "type", name: "Value", bounds: [] };
  const make = (name, params, body) => ({ kind: "function", name, visibility: "crate",
    generics: { parameters: [parameter], wherePredicates: [] }, params,
    returnType: { kind: "primitive", name: "bool" }, body });
  const truth = { statements: [{ kind: "tail", expr: { kind: "bool-literal", value: true } }] };
  const items = finalizeRustSourceStyle({ headerComment, items: [
    make("erased", [], truth),
    make("signature", [{ name: "value", type: { kind: "named", path: "Value" } }], truth),
    make("body", [], { statements: [{ kind: "expr", expr: { kind: "call", path: "retain",
      genericArguments: [{ kind: "type", type: { kind: "named", path: "Value" } }], args: [] } }] }),
  ] }).items;
  assert.deepEqual(items[0].attrs, [rustLintAttributes.unusedTypeParameters]);
  assert.equal(items[1].attrs?.includes(rustLintAttributes.unusedTypeParameters) ?? false, false);
  assert.deepEqual(items[2].attrs ?? [], []);
  const bounded = make("bounded", [{ name: "value", type: { kind: "named", path: "Storage" } }], truth);
  bounded.generics.parameters.push({ kind: "type", name: "Storage", bounds: [{ kind: "trait-type", reference: {
    trait: { kind: "named", path: "rt::OptionalStorage", genericArguments: [{ kind: "type", type: { kind: "named", path: "Value" } }] },
  } }] });
  const boundItem = finalizeRustSourceStyle({ headerComment, items: [bounded] }).items[0];
  assert.equal(boundItem.attrs?.includes(rustLintAttributes.unusedTypeParameters) ?? false, false);
});

test("identical native absence branches preserve conditions without merging different constants", () => {
  const condition = { kind: "call", path: "observe", args: [] };
  const owner = { kind: "named", path: "Option", genericArguments: [{ kind: "type", type: { kind: "primitive", name: "i64" } }] };
  const none = { kind: "associated-value", owner, name: "None" };
  for (const [whenTrue, whenFalse, merged] of [
    [{ kind: "none" }, { kind: "none" }, true],
    [{ kind: "tuple-literal", elements: [] }, { kind: "tuple-literal", elements: [] }, true],
    [none, { ...none }, true],
    [none, { ...none, owner: { kind: "named", path: "Other" } }, false],
    [none, { ...none, trait: { kind: "named", path: "Other" } }, false],
    [{ kind: "call", path: "value", args: [] }, { kind: "call", path: "value", args: [] }, false],
  ]) {
    const conditional = { kind: "conditional", condition, whenTrue, whenFalse };
    const result = finalizeRustSourceStyle({ headerComment, items: [{ kind: "const", name: "VALUE", visibility: "crate",
      type: owner, value: conditional }] }).items[0].value;
    assert.deepEqual(result, merged ? { kind: "evaluate-then", effect: condition, discard: "value", value: whenTrue } : conditional);
  }
});

function printRustSourceFile(model) {
  return printFinalRustSourceFile(finalizeRustSourceStyle(model));
}

test("authored default-then-write order has an exact local style expectation", () => {
  const type = { kind: "named", path: "Options" };
  const initial = { kind: "let", name: "options", mutable: true, type,
    init: { kind: "associated-call", owner: type,
      trait: { kind: "named", path: "core::default::Default" }, method: "default", args: [] } };
  const assignment = { kind: "assign", operator: "=", target: { kind: "field",
    receiver: { kind: "path", path: "options" }, name: "mode" },
    value: { kind: "call", path: "checked_mode", args: [] } };
  for (const [first, second, expected] of [
    [initial, assignment, true],
    [{ ...initial, init: { kind: "call", path: "make_options", args: [] } }, assignment, false],
    [initial, { ...assignment, target: { ...assignment.target, receiver: { kind: "path", path: "other" } } }, false],
    [initial, { kind: "expr", expr: { kind: "call", path: "observe", args: [] } }, false],
    [initial, { ...assignment, value: { kind: "field", receiver: { kind: "path", path: "options" }, name: "old_mode" } }, false],
  ]) {
    const model = finalizeRustSourceStyle({ headerComment, items: [{ kind: "function", name: "options",
      visibility: "public", generics: emptyRustGenerics, params: [], returnType: type,
      body: { statements: [first, second, { kind: "tail", expr: { kind: "path", path: "options" } }] } }] });
    const statements = model.items[0].body.statements;
    assert.deepEqual(model.items[0].body.innerAttrs ?? [], expected ? [rustLintAttributes.fieldReassignWithDefault] : []);
    assert.deepEqual(statements[0].init, first.init);
    assert.deepEqual(statements[1], second);
  }
});

test("source style attributes are item-local and derived from exact Rust signatures", () => {
  const parameters = Array.from({ length: 8 }, (_, index) => ({
    name: `value_${index + 1}`,
    type: index === 0
      ? { kind: "named", path: "Hidden" }
      : { kind: "primitive", name: "i32" },
  }));
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "struct",
      generics: emptyRustGenerics,
      name: "Hidden",
      visibility: "crate",
      fields: [],
    }, {
      kind: "struct",
      generics: emptyRustGenerics,
      name: "Owner",
      visibility: "public",
      fields: [],
    }, {
      kind: "struct",
      generics: emptyRustGenerics,
      name: "InternalCursor",
      visibility: "crate",
      fields: [],
    }, {
      kind: "impl",
      generics: emptyRustGenerics,
      target: { kind: "named", path: "Owner" },
      functions: [{
        name: "to_string",
        generics: emptyRustGenerics,
        visibility: "public",
        selfParam: { kind: "reference", mutable: false },
        params: [],
        returnType: { kind: "string" },
        body: { statements: [{ kind: "tail", expr: { kind: "string-literal", value: "owner" } }] },
      }, {
        name: "next",
        generics: emptyRustGenerics,
        visibility: "public",
        selfParam: { kind: "reference", mutable: true },
        params: [],
        returnType: { kind: "string" },
        body: { statements: [{ kind: "tail", expr: { kind: "string-literal", value: "value" } }] },
      }, {
        name: "configure",
        generics: emptyRustGenerics,
        visibility: "public",
        params: parameters,
        body: { statements: [] },
      }],
    }, {
      kind: "impl",
      generics: emptyRustGenerics,
      target: { kind: "named", path: "InternalCursor" },
      functions: [{
        name: "next",
        generics: emptyRustGenerics,
        visibility: "public",
        selfParam: { kind: "reference", mutable: true },
        params: [],
        returnType: { kind: "string" },
        body: { statements: [{ kind: "tail", expr: { kind: "string-literal", value: "internal" } }] },
      }],
    }],
  });

  assert.match(text, /#\[expect\(clippy::inherent_to_string, reason = "authored toString contract"\)\]\n    pub fn to_string/u);
  assert.match(text, /#\[expect\(clippy::should_implement_trait, reason = "authored method contract"\)\]\n    pub fn next/u);
  assert.match(text, /impl InternalCursor \{\n    pub fn next/u);
  assert.match(
    text,
    /#\[expect\(clippy::too_many_arguments, reason = "checked source signature"\)\]\n    pub fn configure/u,
  );
  assert.match(text, /pub struct Hidden \{\}/u);
  assert.doesNotMatch(text, /private_interfaces/u);
  assert.doesNotMatch(text, /^#!\[allow/mu);
});

test("Iterator naming expectations require the exact mutable-reference receiver", () => {
  for (const [receiver, parameters, expected] of [
    [{ kind: "reference", mutable: true }, [], true],
    [{ kind: "reference", mutable: false }, [], false],
    [{ kind: "value" }, [], false],
    [{ kind: "rc" }, [], false],
    [undefined, [], false],
    [{ kind: "reference", mutable: true }, [{ name: "count", type: { kind: "primitive", name: "i32" } }], false],
  ]) {
    const model = finalizeRustSourceStyle({
      headerComment,
      items: [{
        kind: "struct", generics: emptyRustGenerics, name: "Cursor", visibility: "public", fields: [],
      }, {
        kind: "impl", generics: emptyRustGenerics, target: { kind: "named", path: "Cursor" },
        functions: [{
          name: "next", generics: emptyRustGenerics, visibility: "public", selfParam: receiver,
          params: parameters, returnType: { kind: "primitive", name: "i32" },
          body: { statements: [{ kind: "tail", expr: { kind: "int-literal", text: "1" } }] },
        }],
      }],
    });
    assert.equal(model.items[1].functions[0].attrs?.includes(rustLintAttributes.shouldImplementTrait) ?? false,
      expected, JSON.stringify({ receiver, parameters }));
  }
});

test("source style keeps intentional control-flow policy statement-local", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [
          {
            kind: "if",
            condition: {
              kind: "block",
              bindings: [{ name: "condition", value: { kind: "bool-literal", value: true } }],
              value: { kind: "path", path: "condition" },
            },
            then: {
              statements: [{
                kind: "if",
                condition: { kind: "bool-literal", value: true },
                then: { statements: [] },
              }],
            },
          },
          {
            kind: "for",
            label: "first_value",
            binding: "unused",
            iterable: { kind: "path", path: "values" },
            body: { statements: [{ kind: "break", label: "first_value" }] },
          },
          {
            kind: "tail",
            expr: {
              kind: "call",
              path: "Ok::<_, rt::TsonicError>",
              args: [{
                kind: "try",
                errorDomain: "runtime",
                expr: { kind: "call", path: "fallible", args: [] },
              }],
            },
          },
        ],
      },
    }],
  });

  assert.match(text, /#\[expect\(clippy::blocks_in_conditions, reason = "checked evaluation region"\)\]\n\s*#\[expect\(clippy::collapsible_if, reason = "checked lexical regions"\)\]\n\s*if \{/u);
  assert.match(text, /#\[expect\(unused_variables, reason = "authored binding drop scope"\)\]\n\s*#\[expect\(clippy::never_loop, reason = "authored iterator protocol"\)\]\n\s*'first_value: for unused in values/u);
  assert.match(text, /Ok::<_, rt::TsonicError>\(fallible\(\)\?\)/u);
  assert.doesNotMatch(text, /#!\[allow/u);
});

test("source liveness policy is attached only to proven dead local values", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [{ name: "condition", type: { kind: "primitive", name: "bool" } }],
      body: {
        statements: [
          {
            kind: "let",
            name: "selected",
            mutable: true,
            type: { kind: "primitive", name: "i32" },
            init: { kind: "int-literal", text: "0" },
          },
          {
            kind: "if",
            condition: { kind: "path", path: "condition" },
            then: {
              statements: [{
                kind: "assign",
                target: { kind: "path", path: "selected" },
                operator: "=",
                value: { kind: "int-literal", text: "1" },
              }],
            },
            else: {
              statements: [{
                kind: "assign",
                target: { kind: "path", path: "selected" },
                operator: "=",
                value: { kind: "int-literal", text: "2" },
              }],
            },
          },
          { kind: "expr", expr: { kind: "call", path: "consume", args: [{ kind: "path", path: "selected" }] } },
          { kind: "let", name: "unused", mutable: false, init: { kind: "call", path: "produce", args: [] } },
          { kind: "let", name: "overwritten", mutable: true, init: { kind: "int-literal", text: "0" } },
          {
            kind: "assign",
            target: { kind: "path", path: "overwritten" },
            operator: "=",
            value: { kind: "int-literal", text: "1" },
          },
          {
            kind: "assign",
            target: { kind: "path", path: "overwritten" },
            operator: "=",
            value: { kind: "int-literal", text: "2" },
          },
          { kind: "expr", expr: { kind: "call", path: "consume", args: [{ kind: "path", path: "overwritten" }] } },
          { kind: "let", name: "holder", mutable: true, init: { kind: "call", path: "create_holder", args: [] } },
          {
            kind: "assign",
            target: { kind: "field", receiver: { kind: "path", path: "holder" }, name: "value" },
            operator: "=",
            value: { kind: "int-literal", text: "3" },
          },
          { kind: "expr", expr: { kind: "call", path: "consume", args: [{ kind: "path", path: "holder" }] } },
          { kind: "let", name: "read_only", mutable: true, init: { kind: "call", path: "create_holder", args: [] } },
          { kind: "expr", expr: { kind: "call", path: "consume", args: [{ kind: "path", path: "read_only" }] } },
          { kind: "let", name: "method_mutated", mutable: true, init: { kind: "call", path: "create_holder", args: [] } },
          {
            kind: "expr",
            expr: {
              kind: "method-call",
              receiver: { kind: "path", path: "method_mutated" },
              method: "replace",
              args: [{ kind: "int-literal", text: "4" }],
              receiverMode: "mut-ref",
            },
          },
          { kind: "let", name: "looped", mutable: true, init: { kind: "int-literal", text: "0" } },
          {
            kind: "while",
            condition: { kind: "path", path: "condition" },
            body: {
              statements: [
                {
                  kind: "assign",
                  target: { kind: "path", path: "looped" },
                  operator: "=",
                  value: { kind: "int-literal", text: "1" },
                },
                { kind: "continue" },
              ],
            },
          },
          { kind: "expr", expr: { kind: "call", path: "consume", args: [{ kind: "path", path: "looped" }] } },
        ],
      },
    }],
  });

  assert.match(text, /#\[expect\(unused_assignments, reason = "checked source evaluation order"\)\]\n\s*let mut selected: i32 = 0;/u);
  assert.match(text, /#\[expect\(unused_variables, reason = "authored binding drop scope"\)\]\n\s*let unused = produce\(\);/u);
  assert.match(text, /#\[expect\(unused_assignments, reason = "checked source evaluation order"\)\]\n\s*let mut overwritten = 0;/u);
  assert.match(text, /\{\n\s*#!\[expect\(unused_assignments, reason = "checked source evaluation order"\)\]\n\s*overwritten = 1;\n\s*\}/u);
  assert.doesNotMatch(text, /#\[allow\(unused_assignments[^\n]*\)\]\n\s*selected = [12];/u);
  assert.doesNotMatch(text, /#\[allow\(unused_assignments[^\n]*\)\]\n\s*overwritten = 2;/u);
  assert.match(text, /let mut holder = create_holder\(\);\n\s*holder\.value = 3;/u);
  assert.match(text, /let read_only = create_holder\(\);/u);
  assert.doesNotMatch(text, /let mut read_only/u);
  assert.match(text, /let mut method_mutated = create_holder\(\);\n\s*method_mutated\.replace\(4\);/u);
  assert.doesNotMatch(text, /allow\(unused_assignments[^\n]*\)\]\n\s*looped = 1;/u);
});

test("multiline method-chain arguments use rustfmt-compatible outer-call layout", () => {
  const chain = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: {
        kind: "method-call",
        receiver: { kind: "path", path: "values" },
        method: "get",
        args: [{
          kind: "try",
          expr: {
            kind: "call",
            path: "tsonic_rust_runtime::conversions::i32_to_usize",
            args: [{ kind: "int-literal", text: "1" }],
          },
        }],
      },
      method: "copied",
      args: [],
    },
    method: "is_none",
    args: [],
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: { kind: "call", path: "acme_testing::check", args: [chain] },
        }],
      },
    }],
  });

  assert.match(text, /acme_testing::check\(\n        values\n            \.get\(tsonic_rust_runtime::conversions::i32_to_usize\(1\)\?\)\n            \.copied\(\)\n            \.is_none\(\),\n    \);/u);
});

test("rustfmt canonicalizes nested collection initializers", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "scope",
          body: {
            statements: [{
              kind: "let",
              name: "module_value_3",
              mutable: false,
              init: {
                kind: "call",
                path: "js_abi::JsArray::from_dense",
                args: [{
                  kind: "vec-literal",
                  elements: [{
                    kind: "method-call",
                    receiver: { kind: "path", path: "SELECTED" },
                    method: "with",
                    args: [{
                      kind: "closure",
                      params: [{ name: "module_binding", byRefCopy: false }],
                      body: {
                        kind: "method-call",
                        receiver: { kind: "path", path: "module_binding" },
                        method: "load",
                        args: [],
                      },
                    }],
                  }],
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    text,
    /let module_value_3 = js_abi::JsArray::from_dense\(vec!\[\n {12}SELECTED\.with\(\|module_binding\| module_binding\.load\(\)\),\n {8}\]\);/u,
  );
});

test("fitted multi-argument calls stay horizontal inside assignments", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "manifest" },
          operator: "=",
          value: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_node::fs::read_file_sync_string",
              args: [
                { kind: "str-literal", value: "Cargo.toml" },
                { kind: "str-literal", value: "utf8" },
              ],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /manifest = tsonic_rust_node::fs::read_file_sync_string\("Cargo.toml", "utf8"\)\?;/u);
});

test("assignment continuations keep newly fitting nested calls horizontal", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "stored_collection_key_length" },
          operator: "+=",
          value: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "call",
                path: "js_string::js_len",
                args: [{ kind: "reference", expr: { kind: "path", path: "key" } }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    text,
    /stored_collection_key_length \+=\n        tsonic_rust_runtime::conversions::usize_to_i32\(js_string::js_len\(&key\)\)\?;/u,
  );
});

test("a fitted outer call stays attached to its multiline nested call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "call",
                path: "tsonic_rust_js::string::js_len",
                args: [{
                  kind: "reference",
                  expr: {
                    kind: "call",
                    path: "tsonic_rust_node::os::platform_with_a_deliberately_long_name",
                    args: [],
                  },
                }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /usize_to_i32\(tsonic_rust_js::string::js_len\(\n        &tsonic_rust_node/u);
  assert.doesNotMatch(text, /usize_to_i32\(\n        tsonic_rust_js/u);
});

test("a nested call owns the fitting break inside a wider expression", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: ">",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::usize_to_i32",
                  args: [{
                    kind: "call",
                    path: "js_string::js_len",
                    args: [{
                      kind: "reference",
                      expr: {
                        kind: "call",
                        path: "tsonic_rust_node::os::platform",
                        args: [],
                      },
                    }],
                  }],
                },
              },
              right: { kind: "int-literal", text: "0" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /usize_to_i32\(js_string::js_len\(\n            &tsonic_rust_node::os::platform\(\),\n        \)\)\? > 0/u);
});

test("fallible statement calls reserve the trailing semicolon before fitting nested calls", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "bool-literal", value: true },
          then: {
            statements: [{
              kind: "expr",
              expr: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_node::crypto::random_bytes",
                  args: [{
                    kind: "try",
                    expr: {
                      kind: "call",
                      path: "tsonic_rust_runtime::conversions::i32_to_usize",
                      args: [{ kind: "int-literal", text: "16" }],
                    },
                  }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    text,
    /random_bytes\(tsonic_rust_runtime::conversions::i32_to_usize\(\n {12}16,\n {8}\)\?\)\?/u,
  );
});

test("an outer call stays attached to an expanded fallible inner call", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "receiver" },
            method: "write_value",
            args: [{
              kind: "try",
              expr: {
                kind: "call",
                path: "checked_operation_with_a_deliberately_long_name",
                args: [
                  { kind: "path", path: "first_value_with_a_deliberately_long_name" },
                  { kind: "path", path: "second_value_with_a_deliberately_long_name" },
                ],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /receiver\.write_value\(checked_operation_with_a_deliberately_long_name\(\n/u);
  assert.match(source, /\n    \)\?\);/u);
  assert.doesNotMatch(source, /receiver\.write_value\(\n/u);
});

test("a multiline fallible method chain expands inside its outer call", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "call",
            path: "Ok::<_, rt::TsonicError>",
            args: [{
              kind: "try",
              expr: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "js_string::replace_all",
                  args: [
                    { kind: "reference", expr: { kind: "path", path: "value" } },
                    { kind: "string-literal", value: "a" },
                    { kind: "string-literal", value: "b" },
                  ],
                },
                method: "map_err",
                args: [{
                  kind: "path",
                  path: "tsonic_rust_runtime::TsonicError::from",
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /Ok::<_, rt::TsonicError>\(\n        js_string::replace_all/u);
  assert.match(source, /\.map_err\(tsonic_rust_runtime::TsonicError::from\)\?,\n    \)/u);
});

test("a long outer call expands before a jointly fitting method argument", () => {
  const clone = (name) => ({
    kind: "method-call",
    receiver: { kind: "path", path: name },
    method: "clone",
    args: [],
  });
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "method-call",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "values" },
                  method: "load",
                  args: [],
                },
                method: "push",
                args: [{
                  kind: "try",
                  expr: {
                    kind: "call",
                    path: "nextValue",
                    args: [clone("alias"), clone("calls")],
                  },
                }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /usize_to_i32\(\n        values\.load\(\)\.push\(nextValue\(alias\.clone\(\), calls\.clone\(\)\)\?\),\n    \)\?;/u);
});
