import { test } from "node:test";
import assert from "node:assert/strict";
import { emptyRustGenerics } from "../../../dist/backend/target-ast/nodes.js";
import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("an outer call stays attached to an expanded associated call", () => {
  const optionalLocation = (name) => ({
    kind: "method-call",
    receiver: {
      kind: "call",
      path: "Some",
      args: [{
        kind: "method-call",
        receiver: { kind: "path", path: name },
        method: "clone",
        args: [],
      }],
    },
    method: "as_ref",
    args: [],
  });
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Location",
                genericArguments: [{
                  kind: "type",
                  type: { kind: "primitive", name: "i32" },
                }],
              },
              method: "same",
              args: [optionalLocation("first"), optionalLocation("firstAgain")],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(rt::Location::<i32>::same\(\n        Some\(first\.clone\(\)\)\.as_ref\(\),\n        Some\(firstAgain\.clone\(\)\)\.as_ref\(\),\n    \)\);/u);
});

test("a single block argument stays attached to its outer call", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "run",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
          kind: "call",
          path: "conversion_with_an_intentionally_long_name",
          args: [{
            kind: "block",
            bindings: [{
              name: "location",
              value: { kind: "call", path: "load_location", args: [] },
            }],
            value: {
              kind: "method-call",
              receiver: { kind: "path", path: "location" },
              method: "with_mut",
              args: [{
                kind: "closure",
                params: [{ name: "value", byRefCopy: false }],
                body: { kind: "path", path: "value" },
              }],
            },
          }],
          },
        }],
      },
    }],
  });

  assert.match(source, /conversion_with_an_intentionally_long_name\(\{\n/);
  assert.match(source, /\n    \}\);/);
});

test("a trailing block argument stays attached after preceding arguments", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "run",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "set",
            args: [
              { kind: "string-literal", value: "selected" },
              {
                kind: "block",
                bindings: [{
                  name: "value",
                  value: {
                    kind: "call",
                    path: "make_value_with_an_intentionally_long_name_that_requires_block_expansion",
                    args: [],
                  },
                }],
                value: { kind: "path", path: "value" },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /values\.set\(String::from\("selected"\), \{\n/u);
  assert.match(source, /\n    \}\);/u);
});

test("a trailing fitted closure stays attached after preceding arguments", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "run",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "total",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "reduce_with_array",
            args: [
              { kind: "int-literal", text: "0" },
              {
                kind: "closure",
                params: [
                  { name: "sum", byRefCopy: false },
                  { name: "value", byRefCopy: false },
                  { name: "current", byRefCopy: false },
                  { name: "array", byRefCopy: false },
                ],
                body: {
                  kind: "conditional",
                  condition: {
                    kind: "binary",
                    operator: ">=",
                    left: { kind: "path", path: "current" },
                    right: { kind: "float-literal", text: "0.0" },
                  },
                  whenTrue: {
                    kind: "binary",
                    operator: "+",
                    left: { kind: "path", path: "sum" },
                    right: { kind: "path", path: "value" },
                  },
                  whenFalse: { kind: "path", path: "sum" },
                },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /let total = values\.reduce_with_array\(0, \|sum, value, current, array\| \{\n/u);
  assert.match(source, /\n    \}\);/u);
  assert.doesNotMatch(source, /reduce_with_array\(\n/u);
});

test("three-field struct literals use rustfmt-compatible vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "new_item",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "struct-literal",
            path: "TodoItem",
            fields: [
              { name: "id", value: { kind: "path", path: "id" } },
              { name: "title", value: { kind: "path", path: "title" } },
              { name: "completed", value: { kind: "bool-literal", value: false } },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /TodoItem \{\n        id,\n        title,\n        completed: false,\n    \}/u);
});

test("a fitted condition moves only its overflowing brace", () => {
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "||",
      left: {
        kind: "binary",
        operator: "!=",
        left: { kind: "call", path: "js_abi::math_pow", args: [{ kind: "float-literal", text: "2.0" }, { kind: "float-literal", text: "10.0" }] },
        right: { kind: "float-literal", text: "1024.0" },
      },
      right: {
        kind: "binary",
        operator: "!=",
        left: { kind: "call", path: "absolute_value", args: [{ kind: "float-literal", text: "-5.0" }] },
        right: { kind: "float-literal", text: "5.0" },
      },
    },
    right: {
      kind: "binary",
      operator: "!=",
      left: { kind: "call", path: "truncate_value", args: [{ kind: "float-literal", text: "-2.7" }] },
      right: { kind: "float-literal", text: "-2.0" },
    },
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(source, /truncate_value\(-2\.7\) != -2\.0\n    \{\}/u);
});

test("a block-valued comparison chain keeps its body brace at statement indentation", () => {
  const blockValue = (name, value) => ({
    kind: "block",
    bindings: [{ name, value }],
    value: { kind: "path", path: name },
  });
  const condition = {
    kind: "binary",
    operator: "||",
    left: {
      kind: "binary",
      operator: "||",
      left: {
        kind: "binary",
        operator: "!=",
        left: blockValue("first", { kind: "int-literal", text: "1" }),
        right: { kind: "int-literal", text: "1" },
      },
      right: {
        kind: "binary",
        operator: "!=",
        left: blockValue("second", { kind: "int-literal", text: "2" }),
        right: { kind: "int-literal", text: "2" },
      },
    },
    right: blockValue("third", { kind: "bool-literal", value: false }),
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: { statements: [{ kind: "if", condition, then: { statements: [] } }] },
    }],
  });

  assert.match(source, /        third\n        \}\n    \{\}/u);
  assert.doesNotMatch(source, /        \} \{\}/u);
});

test("conditional expressions move the brace after a multiline method chain", () => {
  const condition = {
    kind: "method-call",
    receiver: {
      kind: "method-call",
      receiver: {
        kind: "method-call",
        receiver: {
          kind: "field",
          receiver: { kind: "path", path: "value" },
          name: "__tsonic_dispatch",
        },
        method: "clone",
        args: [],
      },
      method: "__tsonic_downcast",
      args: [],
    },
    method: "is_some",
    args: [],
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [{ name: "value", type: { kind: "named", path: "Value", genericArguments: [] } }],
      returnType: { kind: "string" },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "conditional",
            condition,
            whenTrue: { kind: "string-literal", value: "yes" },
            whenFalse: { kind: "string-literal", value: "no" },
          },
        }],
      },
    }],
  });

  assert.match(source, /\.is_some\(\)\n    \{\n        String::from\("yes"\)/u);
});

test("short conditional initializers use rustfmt's single-line form", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "choose",
      visibility: "public",
      params: [{ name: "flag", type: { kind: "primitive", name: "bool" } }],
      returnType: { kind: "primitive", name: "i32" },
      body: {
        statements: [
          {
            kind: "let",
            name: "result",
            mutable: false,
            type: { kind: "primitive", name: "i32" },
            init: {
              kind: "conditional",
              condition: { kind: "path", path: "flag" },
              whenTrue: { kind: "int-literal", text: "10" },
              whenFalse: { kind: "int-literal", text: "20" },
            },
          },
          {
            kind: "tail",
            expr: { kind: "path", path: "result" },
          },
        ],
      },
    }],
  });

  assert.match(source, /if flag \{ 10 \} else \{ 20 \}/u);
});

test("comparisons follow multiline arithmetic operands", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: {
            kind: "binary",
            operator: "!=",
            left: {
              kind: "binary",
              operator: "+",
              left: { kind: "call", path: "first_source_value_with_a_deliberately_long_name", args: [] },
              right: { kind: "call", path: "second_source_value_with_a_deliberately_long_name", args: [] },
            },
            right: { kind: "int-literal", text: "7" },
          },
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(source, /first_source_value_with_a_deliberately_long_name\(\)\n        \+ second_source_value_with_a_deliberately_long_name\(\)\n        != 7/u);
});

test("long let-bound method chains stay attached to their receiver", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "module_value_with_a_deliberately_long_generated_identity",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: { kind: "path", path: "second" },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "module_binding", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "module_binding" },
                  method: "location",
                  args: [],
                },
              }],
            },
            method: "clone",
            args: [],
          },
        }],
      },
    }],
  });

  assert.match(source, /let module_value_with_a_deliberately_long_generated_identity = second\n        \.with\(\|module_binding\| module_binding\.location\(\)\)\n        \.clone\(\);/u);
});

test("long field-led method chains use rustfmt selector layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [{ name: "value", type: { kind: "named", path: "Value", genericArguments: [] } }],
      returnType: { kind: "named", path: "bool", genericArguments: [] },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: {
                  kind: "field",
                  receiver: { kind: "path", path: "value" },
                  name: "__tsonic_dispatch",
                },
                method: "clone",
                args: [],
              },
              method: "__tsonic_downcast_2",
              args: [],
            },
            method: "is_some",
            args: [],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /value\n        \.__tsonic_dispatch\n        \.clone\(\)\n        \.__tsonic_downcast_2\(\)\n        \.is_some\(\)/u,
  );
});

test("pure method chains keep the first fitting call attached to their receiver", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "set" },
                method: "add_eq",
                args: [{ kind: "call", path: "first_value", args: [] }],
              },
              method: "add_eq",
              args: [{ kind: "call", path: "second_value", args: [] }],
            },
            method: "add_eq",
            args: [{ kind: "call", path: "third_value", args: [] }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /set\.add_eq\(first_value\(\)\)\n        \.add_eq\(second_value\(\)\)\n        \.add_eq\(third_value\(\)\);/u,
  );
});

test("fitting collection chains keep their first argument-bearing call attached", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: { kind: "path", path: "map" },
              method: "set",
              args: [
                { kind: "call", path: "String::from", args: [{ kind: "str-literal", value: "a" }] },
                { kind: "int-literal", text: "1" },
              ],
            },
            method: "set_discard",
            args: [
              { kind: "call", path: "String::from", args: [{ kind: "str-literal", value: "b" }] },
              { kind: "int-literal", text: "2" },
            ],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /map\.set\(String::from\("a"\), 1\)\n        \.set_discard\(String::from\("b"\), 2\);/u,
  );
});

test("field-led calls stay attached when their argument list must expand", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "field",
              receiver: { kind: "path", path: "dispatch_receiver" },
              name: "dispatch",
            },
            method: "write_counter_value",
            args: [{
              kind: "binary",
              operator: "+",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "field",
                  receiver: { kind: "path", path: "dispatch_receiver" },
                  name: "dispatch",
                },
                method: "read_counter_value",
                args: [],
              },
              right: { kind: "path", path: "value_with_a_long_generated_name" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /dispatch_receiver\.dispatch\.write_counter_value\(\n {8}dispatch_receiver\.dispatch\.read_counter_value\(\) \+ value_with_a_long_generated_name,/u,
  );
});

test("trait signatures count their semicolon and break before long return types", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      generics: emptyRustGenerics,
      name: "Contract",
      visibility: "crate",
      functions: [{
        name: "__tsonic_downcast",
        generics: emptyRustGenerics,
        selfParam: { kind: "rc" },
        params: [],
        returnType: {
          kind: "named",
          path: "Option",
          genericArguments: [{
            kind: "type",
            type: {
              kind: "named",
              path: "std::rc::Rc",
              genericArguments: [{
                kind: "type",
                type: {
                  kind: "trait-object",
                  principal: {
                    trait: {
                      kind: "named",
                      path: "__TsonicDispatch_Leaf",
                      genericArguments: [],
                    },
                  },
                  autoTraits: [],
                },
              }],
            },
          }],
        },
      }],
    }],
  });

  assert.match(
    source,
    /fn __tsonic_downcast\(self: std::rc::Rc<Self>\)\n        -> Option<std::rc::Rc<dyn __TsonicDispatch_Leaf>>;/u,
  );
});

test("one-field struct literals honor rustfmt's compact body limit", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "new_counter",
      params: [],
      body: {
        statements: [
          {
            kind: "let",
            name: "simple",
            mutable: false,
            init: {
              kind: "struct-literal",
              path: "Counter",
              fields: [{ name: "value", value: { kind: "int-literal", text: "1" } }],
            },
          },
          {
            kind: "tail",
            expr: {
              kind: "struct-literal",
              path: "Counter",
              fields: [{
                name: "value",
                value: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "value" },
                  method: "clone",
                  args: [],
                },
              }],
            },
          },
        ],
      },
    }],
  });

  assert.match(source, /let simple = Counter \{ value: 1 \};/u);
  assert.match(source, /Counter \{\n        value: value\.clone\(\),\n    \}/u);
});

test("typed bindings retain overflowing struct openings and expand their fields", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      visibility: "public",
      name: "new_pair",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "pair",
          mutable: false,
          type: {
            kind: "named",
            path: "Pair",
            genericArguments: [{
              kind: "type",
              type: { kind: "named", path: "i32" },
            }],
          },
          init: {
            kind: "struct-literal",
            path: "Pair",
            fields: [{
              name: "__tsonic_state",
              value: {
                kind: "call",
                path: "rt::ObjectHandle::new",
                args: [{
                  kind: "tuple-literal",
                  elements: [
                    { kind: "int-literal", text: "1" },
                    { kind: "call", path: "String::from", args: [{ kind: "str-literal", value: "kept" }] },
                    { kind: "int-literal", text: "2" },
                  ],
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /let pair: Pair<i32> = Pair \{\n        __tsonic_state: rt::ObjectHandle::new/u);
});
