import { test } from "node:test";
import assert from "node:assert/strict";
import { printRustSourceFile } from "../../../dist/print/rust/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("optional closure chains and nested struct arguments stay rustfmt-stable", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      visibility: "public",
      name: "proof",
      params: [],
      body: {
        statements: [
          {
            kind: "expr",
            expr: {
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "value" },
                method: "as_ref",
                args: [],
              },
              method: "map",
              args: [{
                kind: "closure",
                params: [{ name: "selected", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "selected" },
                  method: "operation_with_a_deliberately_long_name_that_requires_a_closure_body_break",
                  args: [],
                },
              }],
            },
          },
          {
            kind: "expr",
            expr: {
              kind: "call",
              path: "read",
              args: [{
                kind: "call",
                path: "Some",
                args: [{
                  kind: "struct-literal",
                  path: "Box",
                  fields: [{
                    name: "state",
                    value: {
                      kind: "call",
                      path: "ObjectHandle::new",
                      args: [{ kind: "int-literal", text: "7" }],
                    },
                  }],
                }],
              }],
            },
          },
          {
            kind: "expr",
            expr: {
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "read",
                  args: [{
                    kind: "call",
                    path: "Some",
                    args: [{
                      kind: "struct-literal",
                      path: "Box",
                      fields: [{
                        name: "state",
                        value: {
                          kind: "call",
                          path: "ObjectHandle::new",
                          args: [{
                            kind: "path",
                            path: "a_deliberately_long_value_name_that_forces_nested_layout",
                          }],
                        },
                      }],
                    }],
                  }],
                },
                method: "unwrap_or",
                args: [{ kind: "unary", operator: "-", operand: { kind: "int-literal", text: "1" } }],
              },
              right: { kind: "int-literal", text: "7" },
            },
          },
        ],
      },
    }],
  });

  assert.match(source, /value\.as_ref\(\)\.map\(\|selected\| \{\n/u);
  assert.match(source, /read\(Some\(Box \{\n        state: ObjectHandle::new\(7\),\n    \}\)\);/u);
  assert.match(source, /read\(Some\(Box \{\n        state: ObjectHandle::new\(a_deliberately_long_value_name_that_forces_nested_layout\),\n    \}\)\)\n    \.unwrap_or\(-1\)\n        == 7;/u);
});

test("long logical chains use rustfmt-compatible operand-per-line layout", () => {
  const terms = Array.from({ length: 7 }, (_, index) => ({
    kind: "binary",
    operator: "!=",
    left: { kind: "call", path: "fibonacci", args: [{ kind: "int-literal", text: String(index) }] },
    right: { kind: "int-literal", text: String(index) },
  }));
  const condition = terms.slice(1).reduce(
    (left, right) => ({ kind: "binary", operator: "||", left, right }),
    terms[0],
  );
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition,
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(text, /if fibonacci\(0\) != 0\n        \|\| fibonacci\(1\) != 1\n        \|\| fibonacci\(2\) != 2/u);
});

test("binary expressions place multiline match operands on a continuation line", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "with_default",
      visibility: "public",
      params: [],
      returnType: { kind: "primitive", name: "i32" },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "binary",
            operator: "+",
            left: {
              kind: "binary",
              operator: "+",
              left: { kind: "path", path: "base" },
              right: { kind: "path", path: "value" },
            },
            right: {
              kind: "match",
              expression: { kind: "path", path: "delta" },
              arms: [{
                pattern: {
                  kind: "tuple-variant",
                  path: "Some",
                  elements: [{ kind: "binding", name: "selected" }],
                },
                expression: { kind: "path", path: "selected" },
              }, {
                pattern: { kind: "path", path: "None" },
                expression: { kind: "int-literal", text: "0" },
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /base\n        \+ value\n        \+ \(match delta \{/u);
});

test("binary expressions join adjacent multiline match operands at the closing delimiter", () => {
  const matchExpression = (name) => ({
    kind: "match",
    expression: { kind: "path", path: name },
    arms: [{
      pattern: {
        kind: "tuple-variant",
        path: "Some",
        elements: [{ kind: "binding", name: "selected" }],
      },
      expression: { kind: "path", path: "selected" },
    }, {
      pattern: { kind: "path", path: "None" },
      expression: { kind: "int-literal", text: "0" },
    }],
  });
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "product",
      visibility: "public",
      params: [],
      returnType: { kind: "primitive", name: "i32" },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "binary",
            operator: "*",
            left: matchExpression("left"),
            right: matchExpression("right"),
          },
        }],
      },
    }],
  });

  assert.match(text, /    \}\) \* \(match right \{/u);
});

test("multiline mixed logical groups preserve source precedence", () => {
  const call = (suffix) => ({
    kind: "call",
    path: `predicate_with_an_intentionally_long_name_${suffix}`,
    args: [{ kind: "path", path: "value" }],
  });
  const condition = {
    kind: "binary",
    operator: "&&",
    left: { kind: "path", path: "enabled" },
    right: {
      kind: "binary",
      operator: "||",
      left: call("left"),
      right: call("right"),
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition,
          then: { statements: [] },
        }],
      },
    }],
  });

  assert.match(text, /enabled\n        && \(predicate_with_an_intentionally_long_name_left\(value\)\n            \|\| predicate_with_an_intentionally_long_name_right\(value\)\)/u);
});

test("statement-valued expressions are parenthesized as binary operands", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      returnType: { kind: "primitive", name: "i32" },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "binary",
            operator: "+",
            left: {
              kind: "block",
              bindings: [{
                name: "selected",
                value: { kind: "int-literal", text: "1" },
              }],
              value: { kind: "path", path: "selected" },
            },
            right: { kind: "int-literal", text: "1" },
          },
        }],
      },
    }],
  });

  assert.match(text, /\(\{\n        let selected = 1;\n        selected\n    \}\) \+ 1/u);
});

test("long assignments break after the assignment operator", () => {
  const conversion = {
    kind: "call",
    path: "tsonic_rust_runtime::conversions::i32_to_usize",
    args: [{ kind: "int-literal", text: "0" }],
  };
  const element = {
    kind: "index",
    receiver: { kind: "path", path: "values" },
    index: { kind: "try", expr: conversion },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: element,
          operator: "=",
          value: {
            kind: "binary",
            operator: "+",
            left: element,
            right: { kind: "int-literal", text: "1" },
          },
        }],
      },
    }],
  });

  assert.match(text, /values\[tsonic_rust_runtime::conversions::i32_to_usize\(0\)\?\] =\n        values\[/u);
});

test("multiline arithmetic assignments break after the assignment operator", () => {
  const value = {
    kind: "binary",
    operator: "+",
    left: {
      kind: "try",
      expr: {
        kind: "call",
        path: "tsonic_rust_runtime::conversions::usize_to_i32",
        args: [{
          kind: "call",
          path: "js_string::js_len",
          args: [{ kind: "reference", expr: { kind: "path", path: "entry.0" } }],
        }],
      },
    },
    right: { kind: "path", path: "entry.1" },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "entryTotal" },
          operator: "+=",
          value,
        }],
      },
    }],
  });

  assert.match(text, /entryTotal \+=\n        tsonic_rust_runtime::conversions::usize_to_i32/u);
});

test("overflowing nested calls retain attached wrappers and jointly fitting arguments", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::isize_to_i32",
              args: [{
                kind: "call",
                path: "example_runtime::canonical_array_index_of",
                args: [
                  { kind: "reference", expr: { kind: "path", path: "values" } },
                  { kind: "reference", expr: { kind: "int-literal", text: "3" } },
                  { kind: "int-literal", text: "0" },
                ],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /isize_to_i32\(example_runtime::canonical_array_index_of\(\n        &values, &3, 0,\n    \)\)\?/u);
});

test("nested calls beyond rustfmt call width put each argument on its own line", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "tsonic_rust_node::url::can_parse",
              args: [
                { kind: "str-literal", value: "https://example.com" },
                { kind: "path", path: "None" },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /can_parse\(\n        "https:\/\/example\.com",\n        None,\n    \)\);/u);
});

test("nested single-argument wrappers stay attached to the expanded inner call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "js_abi::number_is_nan",
              args: [{
                kind: "call",
                path: "js_abi::math_pow",
                args: [
                  { kind: "float-literal", text: "1.0" },
                  { kind: "path", path: "js_abi::NUMBER_POSITIVE_INFINITY" },
                ],
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /check\(js_abi::number_is_nan\(js_abi::math_pow\(\n        1\.0,\n        js_abi::NUMBER_POSITIVE_INFINITY,\n    \)\)\);/u);
});

test("nested single-argument error wrappers expand at the exact innermost value", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "call",
            path: "Err",
            args: [{
              kind: "call",
              path: "rt::TsonicError::from",
              args: [{
                kind: "call",
                path: "DomainError::new",
                args: [{ kind: "string-literal", value: "domain" }],
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    text,
    /Err\(rt::TsonicError::from\(DomainError::new\(String::from\(\n {8}"domain",\n {4}\)\)\)\)/u,
  );
});

test("fallible nested calls in comparisons use rustfmt-compatible wrapper layout", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::isize_to_i32",
                  args: [{
                    kind: "call",
                    path: "js_string::last_index_of_from_end",
                    args: [
                      { kind: "str-literal", value: "banana" },
                      { kind: "str-literal", value: "ana" },
                    ],
                  }],
                },
              },
              right: { kind: "int-literal", text: "3" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /isize_to_i32\(js_string::last_index_of_from_end\(\n            "banana", "ana",\n        \)\)\? == 3/u);
});

test("long borrowed slices use rustfmt-compatible element layout", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "call",
              path: "node_util::format",
              args: [
                { kind: "str-literal", value: "%s:%d" },
                {
                  kind: "reference",
                  expr: {
                    kind: "slice-literal",
                    elements: [
                      {
                        kind: "call",
                        path: "tsonic_rust_js::abi::JsValue::from",
                        args: [{ kind: "string-literal", value: "count" }],
                      },
                      {
                        kind: "call",
                        path: "tsonic_rust_js::abi::JsValue::from",
                        args: [{ kind: "float-literal", text: "3.0" }],
                      },
                    ],
                  },
                },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /&\[\n            tsonic_rust_js::abi::JsValue::from\(String::from\("count"\)\),\n            tsonic_rust_js::abi::JsValue::from\(3\.0\),\n        \],/u);
});

test("single long borrowed slice arguments stay attached to their call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "js_abi::console_log",
            args: [{
              kind: "reference",
              expr: {
                kind: "slice-literal",
                elements: [
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::js_value_from_string",
                    args: [{ kind: "reference", expr: { kind: "path", path: "label" } }],
                  },
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::JsValue::from",
                    args: [{ kind: "float-literal", text: "6.0" }],
                  },
                  {
                    kind: "call",
                    path: "tsonic_rust_js::abi::JsValue::from",
                    args: [{ kind: "bool-literal", value: true }],
                  },
                ],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /js_abi::console_log\(&\[\n        tsonic_rust_js::abi::js_value_from_string\(&label\),\n        tsonic_rust_js::abi::JsValue::from\(6\.0\),\n        tsonic_rust_js::abi::JsValue::from\(true\),\n    \]\);/u);
  assert.doesNotMatch(text, /js_abi::console_log\(\n/u);
});
