import assert from "node:assert/strict";
import { test } from "node:test";

import { emptyRustGenerics } from "../../../dist/backend/target-ast/nodes.js";
import { printRustSourceFile } from "../../helpers/printed-rust-source.mjs";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("field and closure method chains retain rustfmt vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "field",
              receiver: { kind: "path", path: "__tsonic_receiver" },
              name: "__tsonic_state",
            },
            method: "with_mut",
            args: [{
              kind: "closure",
              params: [{ name: "state", byRefCopy: false }],
              body: {
                kind: "binary",
                operator: "+=",
                left: { kind: "path", path: "state.0" },
                right: { kind: "path", path: "__tsonic_value" },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /__tsonic_receiver\n        \.__tsonic_state\n        \.with_mut/u,
  );
});

test("compact field receivers stay attached before expanded closure calls", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "field",
              receiver: { kind: "path", path: "self" },
              name: "state",
            },
            method: "with_mut",
            args: [{
              kind: "closure",
              params: [{ name: "state", byRefCopy: false }],
              body: {
                kind: "assignment",
                operator: "=",
                target: { kind: "path", path: "state.method_override" },
                value: {
                  kind: "call",
                  path: "Some",
                  args: [{ kind: "path", path: "value" }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /self\.state\n        \.with_mut\(\|state\| state\.method_override = Some\(value\)\)/u,
  );
});

test("let-bound index closures retain rustfmt's vertical method-chain layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "index_current",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: {
              kind: "field",
              receiver: { kind: "path", path: "index_receiver_2" },
              name: "state",
            },
            method: "with",
            args: [{
              kind: "closure",
              params: [{ name: "state", byRefCopy: false }],
              body: {
                kind: "index",
                receiver: {
                  kind: "field",
                  receiver: { kind: "path", path: "state" },
                  name: "index_entries",
                },
                index: {
                  kind: "reference",
                  expr: { kind: "path", path: "index_key_2" },
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let index_current = index_receiver_2\n        \.state\n        \.with\(\|state\| state\.index_entries\[&index_key_2\]\);/u,
  );
});

test("long indexes continue after one-line method-chain receivers", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "index",
            receiver: {
              kind: "method-call",
              receiver: {
                kind: "field",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "holder" },
                  method: "clone",
                  args: [],
                },
                name: "__tsonic_state",
              },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "state", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "state.0" },
                  method: "clone",
                  args: [],
                },
              }],
            },
            index: {
              kind: "try",
              expr: {
                kind: "call",
                path: "tsonic_rust_runtime::conversions::i32_to_usize",
                args: [{ kind: "int-literal", text: "1" }],
              },
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /holder\.clone\(\)\.__tsonic_state\.with\(\|state\| state\.0\.clone\(\)\)\n        \[tsonic_rust_runtime::conversions::i32_to_usize\(1\)\?\];/u,
  );
});

test("multiline method-call match arms use rustfmt block arms", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "match",
            expression: { kind: "path", path: "shape" },
            arms: [{
              pattern: {
                kind: "tuple-variant",
                path: "Shape::Variant0",
                elements: [{
                  kind: "binding",
                  name: "__tsonic_union_variant_with_a_long_identity",
                }],
              },
              expression: {
                kind: "method-call",
                receiver: {
                  kind: "path",
                  path: "__tsonic_union_variant_with_a_long_identity",
                },
                method: "with",
                args: [{
                  kind: "closure",
                  params: [{ name: "state", byRefCopy: false }],
                  body: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "state.0" },
                    method: "clone",
                    args: [],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /Shape::Variant0\(__tsonic_union_variant_with_a_long_identity\) => \{\n            __tsonic_union_variant_with_a_long_identity\.with\(\|state\| state\.0\.clone\(\)\)\n        \}/u,
  );
});

test("direct fallible match arms stay in rustfmt expression form", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "match",
            expression: { kind: "path", path: "command" },
            arms: [{
              pattern: {
                kind: "tuple-variant",
                path: "Command::Throw",
                elements: [{ kind: "binding", name: "error" }],
              },
              expression: {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "call",
                  path: "Err",
                  args: [{ kind: "path", path: "error" }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /Command::Throw\(error\) => Err\(error\)\?,/u);
  assert.doesNotMatch(source, /Command::Throw\(error\) => \{/u);
});

test("rustfmt preserves direct fallible match arms without synthetic blocks", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "match",
            expression: { kind: "path", path: "selected" },
            arms: [{
              pattern: {
                kind: "tuple-variant",
                path: "Some",
                elements: [{ kind: "binding", name: "property_getter_2" }],
              },
              expression: {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "property_getter_2" },
                  method: "call",
                  args: [{
                    kind: "tuple-literal",
                    elements: [{
                      kind: "method-call",
                      receiver: { kind: "path", path: "property_receiver_2" },
                      method: "clone",
                      args: [],
                    }],
                  }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /Some\(property_getter_2\) => property_getter_2\.call\(\(property_receiver_2\.clone\(\),\)\)\?,/u,
  );
  assert.doesNotMatch(source, /Some\(property_getter_2\) => \{/u);
});

test("calls expand matches whose scrutinee contains a statement block", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "Some",
            args: [{
              kind: "match",
              expression: {
                kind: "method-call",
                receiver: {
                  kind: "block",
                  bindings: [{
                    name: "dispatch_receiver",
                    value: { kind: "reference", expr: { kind: "path", path: "project_this" } },
                  }],
                  value: {
                    kind: "method-call",
                    receiver: {
                      kind: "field",
                      receiver: { kind: "path", path: "dispatch_receiver" },
                      name: "dispatch",
                    },
                    method: "read_json_object_value",
                    args: [],
                  },
                },
                method: "as_ref",
                args: [],
              },
              arms: [{
                pattern: {
                  kind: "tuple-variant",
                  path: "Some",
                  elements: [{ kind: "binding", name: "flow_value" }],
                },
                expression: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "flow_value" },
                  method: "clone",
                  args: [],
                },
              }, {
                pattern: { kind: "path", path: "None" },
                expression: { kind: "unreachable", message: "flow fact" },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /Some\(\n {8}match \{/u);
  assert.match(source, /\n {8}\},\n {4}\);/u);
  assert.doesNotMatch(source, /Some\(match \{/u);
});

test("two-selector method arguments retain rustfmt vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "values" },
                method: "get",
                args: [{
                  kind: "try",
                  expr: {
                    kind: "call",
                    path: "tsonic_rust_runtime::conversions::i32_to_usize",
                    args: [{ kind: "int-literal", text: "1" }],
                  },
                }],
              },
              method: "is_none",
              args: [],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(\n        values\n            \.get/u);
});

test("selectors after multiline call bases align with the base", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "call",
                  path: "read",
                  args: [{
                    kind: "struct-literal",
                    path: "Box",
                    fields: [
                      { name: "first_component", value: { kind: "string-literal", value: "first-long-component" } },
                      { name: "second_component", value: { kind: "string-literal", value: "second-long-component" } },
                      { name: "third_component", value: { kind: "string-literal", value: "third-long-component" } },
                    ],
                  }],
                },
                method: "unwrap_or",
                args: [{ kind: "int-literal", text: "-1" }],
              },
              right: { kind: "int-literal", text: "7" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /\n        \.unwrap_or\(-1\)/u);
  assert.doesNotMatch(source, /\n            \.unwrap_or\(-1\)/u);
});

test("long multiline let initializers reflow from their continuation column", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "textFunction",
          mutable: false,
          init: {
            kind: "associated-call",
            owner: {
              kind: "named",
              path: "rt::Callable",
              genericArguments: [
                {
                  kind: "type",
                  type: { kind: "tuple", elements: [{ kind: "string" }] },
                },
                { kind: "type", type: { kind: "string" } },
              ],
            },
            method: "new",
            args: [{
              kind: "closure-block",
              params: [{
                name: "__tsonic_callable_arguments_5",
                mutable: false,
              }],
              move: true,
              async: false,
              body: {
                statements: [{
                  kind: "tail",
                  expr: {
                    kind: "call",
                    path: "preserveText",
                    args: [{
                      kind: "field",
                      receiver: { kind: "path", path: "__tsonic_callable_arguments_5" },
                      name: "0",
                    }],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let textFunction =\n        rt::Callable::<\(String,\), String>::new\(move \|__tsonic_callable_arguments_5\| \{/u,
  );
});

test("fitting callable closures move below long let bindings without expanding", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "record_method_2",
          mutable: false,
          init: {
            kind: "associated-call",
            owner: {
              kind: "named",
              path: "rt::Callable",
              genericArguments: [
                {
                  kind: "type",
                  type: {
                    kind: "tuple",
                    elements: [{ kind: "named", path: "TextReader" }],
                  },
                },
                { kind: "type", type: { kind: "string" } },
              ],
            },
            method: "new",
            args: [{
              kind: "closure",
              params: [{ name: "object_this_2", mutable: false }],
              body: {
                kind: "call",
                path: "String::from",
                args: [{ kind: "str-literal", value: "seven" }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let record_method_2 =\n        rt::Callable::<\(TextReader,\), String>::new\(\|object_this_2\| String::from\("seven"\)\);/u,
  );
});

test("field-led calls break before selectors when the final call fits there", () => {
  const receiver = { kind: "path", path: "dispatch_receiver" };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "field", receiver, name: "dispatch" },
            method: "write_counter_value",
            args: [{
              kind: "binary",
              operator: "+",
              left: {
                kind: "method-call",
                receiver: { kind: "field", receiver, name: "dispatch" },
                method: "read_counter_value",
                args: [],
              },
              right: { kind: "path", path: "value" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /dispatch_receiver\n        \.dispatch\n        \.write_counter_value\(dispatch_receiver\.dispatch\.read_counter_value\(\) \+ value\)/u,
  );
});

test("deep field-led calls keep their callable attached when arguments must expand", () => {
  const receiver = { kind: "path", path: "dispatch_receiver_10" };
  const invocation = {
    kind: "method-call",
    receiver: { kind: "field", receiver, name: "dispatch" },
    method: "write_counter_value",
    args: [{
      kind: "binary",
      operator: "+",
      left: {
        kind: "method-call",
        receiver: { kind: "field", receiver, name: "dispatch" },
        method: "read_counter_value",
        args: [],
      },
      right: { kind: "path", path: "value_5" },
    }],
  };
  const nestedScope = (depth) => depth === 0
    ? { statements: [{ kind: "expr", expr: invocation }] }
    : { statements: [{ kind: "scope", body: nestedScope(depth - 1) }] };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: nestedScope(4),
    }],
  });

  assert.match(
    source,
    /dispatch_receiver_10\.dispatch\.write_counter_value\(\n                        dispatch_receiver_10\.dispatch\.read_counter_value\(\) \+ value_5,\n                    \)/u,
  );
});
