import assert from "node:assert/strict";
import { test } from "node:test";

import { emptyRustGenerics } from "../../../dist/backend/target-ast/nodes.js";
import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("rustfmt-stable calls, closures, conditionals, and borrowed fallible chains", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "field_label",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: { kind: "path", path: "label" },
              method: "clone",
              args: [],
            }, {
              kind: "path",
              path: "std::convert::identity",
            }, {
              kind: "closure",
              params: [],
              body: {
                kind: "owned-string-from-borrowed-str",
                expression: { kind: "str-literal", value: "none" },
              },
            }],
          },
        }, {
          kind: "let",
          name: "loud",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "conditional",
            condition: { kind: "path", path: "selected" },
            whenTrue: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "READY" }],
            },
            whenFalse: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "SET" }],
            },
          },
        }, {
          kind: "expr",
          expr: {
            kind: "string-concat",
            parts: [{
              kind: "owned-string-from-borrowed-str",
              expression: { kind: "str-literal", value: ":" },
            }, {
              kind: "call",
              path: "rt::option_coalesce",
              args: [{
                kind: "field",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "values" },
                  method: "clone",
                  args: [],
                },
                name: "1",
              }, {
                kind: "path",
                path: "std::convert::identity",
              }, {
                kind: "closure",
                params: [],
                body: { kind: "string-literal", value: "none" },
              }],
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "string-concat",
            parts: [{
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }, {
              kind: "call",
              path: "rt::source_string",
              args: [{
                kind: "reference",
                expr: {
                  kind: "try",
                  errorDomain: "runtime",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "callable" },
                    method: "call",
                    args: [{
                      kind: "tuple-literal",
                      elements: [{
                        kind: "try",
                        errorDomain: "runtime",
                        expr: {
                          kind: "call",
                          path: "tsonic_rust_runtime::conversions::f64_to_i32",
                          args: [{ kind: "float-literal", text: "3.0" }],
                        },
                      }, {
                        kind: "call",
                        path: "Some",
                        args: [{
                          kind: "call",
                          path: "String::from",
                          args: [{ kind: "str-literal", value: "bound" }],
                        }],
                      }],
                    }],
                  },
                },
              }],
            }, {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: { kind: "path", path: "value" },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "state", mutable: false }],
                body: {
                  kind: "field",
                  receiver: { kind: "path", path: "state" },
                  name: "id",
                },
              }],
            }, {
              kind: "path",
              path: "Ok",
            }, {
              kind: "closure",
              params: [],
              body: {
                kind: "call",
                path: "tsonic_rust_runtime::conversions::f64_to_i32",
                args: [{ kind: "float-literal", text: "0.0" }],
              },
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "call_bound",
            args: [{ kind: "path", path: "receiver" }, {
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Callable",
                genericArguments: [{
                  kind: "type",
                  type: {
                    kind: "tuple",
                    elements: [
                      { kind: "primitive", name: "i32" },
                      {
                        kind: "named",
                        path: "Option",
                        genericArguments: [{ kind: "type", type: { kind: "string" } }],
                      },
                    ],
                  },
                }, {
                  kind: "type",
                  type: {
                    kind: "named",
                    path: "rt::TsonicResult",
                    genericArguments: [{ kind: "type", type: { kind: "string" } }],
                  },
                }],
              },
              method: "new",
              args: [{
                kind: "closure-block",
                params: [{ name: "callable_arguments", mutable: false }],
                move: true,
                async: false,
                body: {
                  statements: [{
                    kind: "tail",
                    expr: {
                      kind: "call",
                      path: "Ok::<_, rt::TsonicError>",
                      args: [{ kind: "path", path: "callable_arguments.1" }],
                    },
                  }],
                },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let field_label: String =\n {8}rt::option_coalesce\(label\.clone\(\), std::convert::identity, \|\| String::from\("none"\)\);/u,
  );
  assert.match(
    source,
    /let loud: String = if selected \{\n {8}String::from\("READY"\)\n {4}\} else \{\n {8}String::from\("SET"\)\n {4}\};/u,
  );
  assert.match(
    source,
    /rt::option_coalesce\(values\.clone\(\)\.1, std::convert::identity, \|\| String::from\(\n {12}"none"\n {8}\),\),/u,
  );
  assert.match(
    source,
    /rt::source_string\(&callable\.call\(\(\n/u,
  );
  assert.match(
    source,
    /rt::option_coalesce\(value\.with\(\|state\| state\.id\), Ok, \|\| \{\n {8}tsonic_rust_runtime::conversions::f64_to_i32\(0\.0\)\n {4}\}\);/u,
  );
  assert.match(
    source,
    /rt::Callable::<\(i32, Option<String>\), rt::TsonicResult<String>>::new\(/u,
  );
  assert.doesNotMatch(source, /rt::Callable::<\n/u);
});

test("assignment matches retain their enclosing block indentation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "select",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "path", path: "enabled" },
          then: {
            statements: [{
              kind: "assign",
              target: { kind: "path", path: "selected" },
              operator: "=",
              value: {
                kind: "match",
                expression: {
                  kind: "method-call",
                  receiver: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "values" },
                    method: "get_number",
                    args: [{ kind: "path", path: "index" }],
                  },
                  method: "as_ref",
                  args: [],
                },
                arms: [{
                  pattern: {
                    kind: "tuple-variant",
                    path: "Some",
                    elements: [{ kind: "binding", name: "value" }],
                  },
                  expression: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "value" },
                    method: "clone",
                    args: [],
                  },
                }, {
                  pattern: { kind: "path", path: "None" },
                  expression: {
                    kind: "unreachable",
                    message: "checked flow selected a missing optional value",
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /        selected = match values\.get_number\(index\)\.as_ref\(\) \{\n            Some\(value\) => value\.clone\(\),\n            None => unreachable!/u,
  );
  assert.doesNotMatch(source, /\n\.get_number|\nmatch values/u);
});

test("nested wrappers retain every argument when the first argument is a long string", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "fail",
      visibility: "public",
      params: [],
      errorType: { kind: "named", path: "Failure" },
      body: {
        statements: [{
          kind: "throw",
          error: {
            kind: "call",
            path: "Failure::from_diagnostic",
            args: [{
              kind: "call",
              path: "create_diagnostic",
              args: [
                { kind: "string-literal", value: "A_DIAGNOSTIC_CODE_THAT_REQUIRES_FITTING" },
                { kind: "path", path: "message" },
                { kind: "path", path: "source_path" },
                { kind: "path", path: "line" },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /create_diagnostic\(/u);
  assert.match(source, /message,/u);
  assert.match(source, /source_path,/u);
  assert.match(source, /line,/u);
});
