import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../../../dist/print/rust/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("borrowed method-chain let initializers reflow as one continuation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "__tsonic_location",
          mutable: false,
          init: {
            kind: "reference",
            expr: {
              kind: "method-call",
              receiver: { kind: "path", path: "defaultEvaluations" },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "__tsonic_module_binding", mutable: false }],
                move: false,
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "__tsonic_module_binding" },
                  method: "location",
                  args: [],
                },
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let __tsonic_location =\n        &defaultEvaluations\.with\(\|__tsonic_module_binding\| __tsonic_module_binding\.location\(\)\);/u,
  );
});

test("typed let bindings keep fitting call openings before expanded arrays", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "concatenated",
          mutable: false,
          type: {
            kind: "named",
            path: "js_abi::JsArray",
            typeArguments: [{ kind: "primitive", name: "i32" }],
          },
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "concatLeft" },
            method: "concat",
            args: [{
              kind: "slice-literal",
              elements: [
                {
                  kind: "call",
                  path: "js_abi::JsArrayConcatItem::Value",
                  args: [{ kind: "int-literal", text: "4" }],
                },
                {
                  kind: "call",
                  path: "js_abi::JsArrayConcatItem::Array",
                  args: [{ kind: "path", path: "concatRight" }],
                },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let concatenated: js_abi::JsArray<i32> = concatLeft\.concat\(\[\n/u,
  );
});

test("typed let bindings keep expanded ordinary calls attached", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "point",
          mutable: false,
          type: { kind: "primitive", name: "f64" },
          init: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "call",
              path: "js_string::code_point_at",
              args: [
                { kind: "reference", expr: { kind: "path", path: "text" } },
                { kind: "float-literal", text: "0.0" },
              ],
            }, {
              kind: "path",
              path: "std::convert::identity",
            }, {
              kind: "closure",
              params: [],
              body: { kind: "float-literal", text: "0.0" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let point: f64 = rt::option_coalesce\(\n {8}js_string::code_point_at\(&text, 0\.0\),\n {8}std::convert::identity,\n {8}\|\| 0\.0,\n {4}\);/u,
  );
});

test("typed let bindings keep a fitting call base before a fallible selector", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "temporary",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "try",
            expr: {
              kind: "method-call",
              receiver: {
                kind: "call",
                path: "tsonic_rust_node::fs::mkdtemp_sync",
                args: [{ kind: "reference", expr: { kind: "path", path: "root" } }],
              },
              method: "map_err",
              args: [{ kind: "path", path: "tsonic_rust_runtime::TsonicError::from" }],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let temporary: String = tsonic_rust_node::fs::mkdtemp_sync\(&root\)\n        \.map_err\(tsonic_rust_runtime::TsonicError::from\)\?;/u,
  );
});

test("typed let bindings move an expanded call base to one continuation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "merged",
          mutable: false,
          type: { kind: "named", path: "tsonic_rust_node::buffer::Buffer" },
          init: {
            kind: "try",
            expr: {
              kind: "method-call",
              receiver: {
                kind: "associated-call",
                owner: { kind: "named", path: "tsonic_rust_node::buffer::Buffer" },
                method: "concat",
                args: [{
                  kind: "reference",
                  expr: {
                    kind: "call",
                    path: "js_abi::JsArray::from_dense",
                    args: [{
                      kind: "vec-literal",
                      elements: [
                        { kind: "call", path: "clone_first", args: [] },
                        { kind: "call", path: "clone_second", args: [] },
                      ],
                    }],
                  },
                }],
              },
              method: "map_err",
              args: [{ kind: "path", path: "rt::TsonicError::from" }],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let merged: tsonic_rust_node::buffer::Buffer =\n        tsonic_rust_node::buffer::Buffer::concat\(&js_abi::JsArray::from_dense\(vec!\[/u,
  );
});

test("fitting string concatenations remain on typed binding lines", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "file",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "string-concat",
            parts: [
              { kind: "path", path: "temporary" },
              { kind: "path", path: "separator" },
              {
                kind: "call",
                path: "String::from",
                args: [{ kind: "str-literal", value: "payload.bin" }],
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let file: String = format!\("\{\}\{\}\{\}", temporary, separator, String::from\("payload\.bin"\)\);/u,
  );
});

test("fallible method calls keep short receivers attached to block arguments", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "method-call",
              receiver: { kind: "path", path: "values" },
              method: "try_for_each",
              args: [{
                kind: "block",
                bindings: [{
                  name: "captured",
                  value: { kind: "path", path: "source" },
                }],
                value: {
                  kind: "closure",
                  params: [{ name: "value", mutable: false }],
                  move: true,
                  body: {
                    kind: "call",
                    path: "consume",
                    args: [
                      { kind: "path", path: "captured" },
                      { kind: "path", path: "value" },
                    ],
                  },
                },
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /values\.try_for_each\(\{\n/u);
  assert.doesNotMatch(source, /values\n\s+\.try_for_each/u);
});

test("fallible method calls keep short receivers attached to closure blocks", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "method-call",
              receiver: { kind: "path", path: "values" },
              method: "try_sort",
              args: [{
                kind: "closure-block",
                params: [
                  { name: "left", mutable: false },
                  { name: "right", mutable: false },
                ],
                move: false,
                async: false,
                body: {
                  statements: [{
                    kind: "tail",
                    expr: {
                      kind: "call",
                      path: "compare_with_a_deliberately_long_checked_operation",
                      args: [
                        { kind: "path", path: "left" },
                        { kind: "path", path: "right" },
                      ],
                    },
                  }],
                },
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /values\.try_sort\(\|left, right\| \{/u);
  assert.doesNotMatch(source, /values\n\s+\.try_sort/u);
});

test("long expression closures use a vertical receiver before expanding the closure body", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "bool-literal", value: true },
          then: {
            statements: [{
              kind: "if",
              condition: { kind: "bool-literal", value: true },
              then: {
                statements: [{
                  kind: "expr",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "__tsonic_capture_visits" },
                    method: "update_with",
                    args: [{
                      kind: "closure",
                      params: [{ name: "__tsonic_location_current", byRefCopy: false }],
                      body: {
                        kind: "binary",
                        operator: "+",
                        left: { kind: "path", path: "__tsonic_location_current" },
                        right: { kind: "int-literal", text: "1" },
                      },
                    }],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /__tsonic_capture_visits\n                \.update_with\(\|__tsonic_location_current\| __tsonic_location_current \+ 1\);/u,
  );
});

test("short optional chains stay attached when their fitted closure body expands", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "method-call",
            receiver: {
              kind: "method-call",
              receiver: { kind: "path", path: "item" },
              method: "as_ref",
              args: [],
            },
            method: "map",
            args: [{
              kind: "closure",
              params: [{ name: "__tsonic_optional_receiver", byRefCopy: false }],
              body: {
                kind: "method-call",
                receiver: {
                  kind: "field",
                  receiver: { kind: "path", path: "__tsonic_optional_receiver" },
                  name: "__tsonic_state",
                },
                method: "with",
                args: [{
                  kind: "closure",
                  params: [{ name: "state", byRefCopy: false }],
                  body: { kind: "field", receiver: { kind: "path", path: "state" }, name: "0" },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /item\.as_ref\(\)\.map\(\|__tsonic_optional_receiver\| \{/u);
});

test("long multi-supertrait headers use rustfmt-compatible vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_CompleteProjectObject",
      visibility: "private",
      superTraits: [
        { kind: "named", path: "__TsonicDispatch_TaggedProjectObject" },
        { kind: "named", path: "__TsonicDispatch_CountedProjectObject" },
      ],
      functions: [],
    }],
  });

  assert.match(
    source,
    /trait __TsonicDispatch_CompleteProjectObject:\n    __TsonicDispatch_TaggedProjectObject \+ __TsonicDispatch_CountedProjectObject\n\{\n\}/u,
  );
});

test("one long supertrait header uses rustfmt-compatible vertical layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_ProjectObjectWithAnIntentionallyLongContractName",
      visibility: "private",
      superTraits: [{
        kind: "named",
        path: "__TsonicDispatch_ProjectObjectWithAnIntentionallyLongBaseContractName",
      }],
      functions: [],
    }],
  });

  assert.match(
    source,
    /trait __TsonicDispatch_ProjectObjectWithAnIntentionallyLongContractName:\n    __TsonicDispatch_ProjectObjectWithAnIntentionallyLongBaseContractName\n\{\n\}/u,
  );
});

test("one supertrait header below rustfmt width remains on one line", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_StringValue",
      visibility: "crate",
      superTraits: [{
        kind: "named",
        path: "__TsonicDispatch_GenericBase<String>",
      }],
      functions: [],
    }],
  });

  assert.match(
    source,
    /pub\(crate\) trait __TsonicDispatch_StringValue: __TsonicDispatch_GenericBase<String> \{\}/u,
  );
});

test("nonempty traits use rustfmt-compatible long supertrait headers", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_UnsafeImplementation",
      visibility: "crate",
      superTraits: [{
        kind: "named",
        path: "__TsonicDispatch_UnsafeContract",
      }],
      functions: [{
        name: "read",
        selfParam: "rc",
        params: [{ name: "value", type: { kind: "primitive", name: "i32" } }],
        returnType: { kind: "primitive", name: "i32" },
      }],
    }],
  });

  assert.match(
    source,
    /pub\(crate\) trait __TsonicDispatch_UnsafeImplementation:\n    __TsonicDispatch_UnsafeContract\n\{\n/u,
  );
});

test("nonempty traits retain rustfmt-compatible fitted supertrait headers", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "trait",
      name: "__TsonicDispatch_StringValue",
      visibility: "crate",
      superTraits: [{
        kind: "named",
        path: "__TsonicDispatch_GenericBase<String>",
      }],
      functions: [{
        name: "read",
        selfParam: "rc",
        params: [],
        returnType: { kind: "named", path: "String" },
      }],
    }],
  });

  assert.match(
    source,
    /pub\(crate\) trait __TsonicDispatch_StringValue: __TsonicDispatch_GenericBase<String> \{\n/u,
  );
});

test("string concatenation preserves vertical chains inside trailing blocks", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "append",
      visibility: "private",
      params: [],
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "string-concat",
            parts: [
              { kind: "path", path: "current" },
              {
                kind: "block",
                bindings: [{
                  name: "receiver_with_a_deliberately_long_name",
                  value: { kind: "path", path: "value" },
                }],
                value: {
                  kind: "method-call",
                  receiver: {
                    kind: "method-call",
                    receiver: {
                      kind: "field",
                      receiver: { kind: "path", path: "receiver_with_a_deliberately_long_name" },
                      name: "__tsonic_state_with_a_deliberately_long_name",
                    },
                    method: "load_the_complete_project_state_without_inference",
                    args: [],
                  },
                  method: "clone_the_exact_selected_value",
                  args: [],
                },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /format!\("\{\}\{\}", current, \{/u);
  assert.match(
    source,
    /receiver_with_a_deliberately_long_name\n            \.__tsonic_state_with_a_deliberately_long_name\n            \.load_the_complete_project_state_without_inference\(\)\n            \.clone_the_exact_selected_value\(\)/u,
  );
});

test("long struct field types use rustfmt-compatible continuation indentation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "struct",
      name: "DispatchRoot",
      visibility: "private",
      derives: [],
      fields: [{
        name: "dispatch_identity_identity_specialization_1_implementation",
        visibility: "private",
        type: {
          kind: "named",
          path: "rt::Callable",
          typeArguments: [{
            kind: "tuple",
            elements: [
              { kind: "named", path: "Identity" },
              { kind: "named", path: "String" },
            ],
          }, { kind: "named", path: "String" }],
        },
      }],
    }],
  });

  assert.match(
    source,
    /dispatch_identity_identity_specialization_1_implementation:\n {8}rt::Callable<\(Identity, String\), String>,/u,
  );
});
