import { test } from "node:test";
import assert from "node:assert/strict";
import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("single long owned array arguments stay attached to their call", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: { parameters: [], wherePredicates: [] },
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "push_many",
            args: [{
              kind: "slice-literal",
              elements: [
                {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::f64_to_i32",
                  args: [{ kind: "float-literal", text: "2.0" }],
                },
                {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::f64_to_i32",
                  args: [{ kind: "float-literal", text: "3.0" }],
                },
              ],
            }],
          },
        }],
      },
    }],
  });

  assert.match(text, /values\.push_many\(\[\n        tsonic_rust_runtime::conversions::f64_to_i32\(2\.0\),\n        tsonic_rust_runtime::conversions::f64_to_i32\(3\.0\),\n    \]\);/u);
  assert.doesNotMatch(text, /values\.push_many\(\n/u);
});

test("logical assignment keeps a fitting first operand beside the operator", () => {
  const first = {
    kind: "call",
    path: "js_string::includes",
    args: [
      { kind: "reference", expr: { kind: "path", path: "rendered" } },
      { kind: "str-literal", value: "tsonic" },
      { kind: "int-literal", text: "0" },
    ],
  };
  const condition = {
    kind: "binary",
    operator: "&&",
    left: {
      kind: "binary",
      operator: "&&",
      left: first,
      right: { kind: "call", path: "digits.test", args: [{ kind: "str-literal", value: "a12" }] },
    },
    right: {
      kind: "binary",
      operator: "==",
      left: { kind: "path", path: "date_value_with_an_intentionally_long_name_for_rustfmt" },
      right: { kind: "int-literal", text: "1" },
    },
  };
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: { parameters: [], wherePredicates: [] },
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "assign",
          target: { kind: "path", path: "passed" },
          operator: "=",
          value: condition,
        }],
      },
    }],
  });

  assert.match(text, /passed = js_string::includes\(&rendered, "tsonic", 0\)\n        && digits\.test/u);
});

test("fitting fallible statement calls remain horizontal", () => {
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: { parameters: [], wherePredicates: [] },
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_node::fs::write_file_sync_string",
              args: [
                { kind: "reference", expr: { kind: "path", path: "file" } },
                { kind: "str-literal", value: "payload" },
                { kind: "str-literal", value: "utf8" },
              ],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /write_file_sync_string\(&file, "payload", "utf8"\)\?;/u);
});

test("expanded method arguments stay attached to one outer conversion wrapper", () => {
  const convertedElements = ["2.0", "3.0"].map((text) => ({
    kind: "try",
    expr: {
      kind: "call",
      path: "tsonic_rust_runtime::conversions::f64_to_i32",
      args: [{ kind: "float-literal", text }],
    },
  }));
  const text = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: { parameters: [], wherePredicates: [] },
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "method-call",
                receiver: { kind: "path", path: "values" },
                method: "push_many",
                args: [{ kind: "slice-literal", elements: convertedElements }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(text, /usize_to_i32\(values\.push_many\(\[\n[\s\S]*?\n\s+\]\)\)\?;/u);
  assert.doesNotMatch(text, /usize_to_i32\(\n/u);
});
