import assert from "node:assert/strict";
import { test } from "node:test";

import { emptyRustGenerics } from "../../../dist/backend/target-ast/nodes.js";
import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("fitting method-call arguments remain on one rustfmt line", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "method-call",
              receiver: {
                kind: "call",
                path: "tsonic_rust_node::process::env_get",
                args: [{ kind: "str-literal", value: "R7_UNSET_VAR_PROOF" }],
              },
              method: "is_none",
              args: [],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /acme_testing::check\(tsonic_rust_node::process::env_get\("R7_UNSET_VAR_PROOF"\)\.is_none\(\)\);/u,
  );
});

test("single binary call arguments retain rustfmt's attached continuation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "selected",
      visibility: "public",
      params: [],
      returnType: {
        kind: "named",
        path: "Result",
        genericArguments: [
          { kind: "type", type: { kind: "primitive", name: "i32" } },
          { kind: "type", type: { kind: "named", path: "Error" } },
        ],
      },
      body: {
        statements: [{
          kind: "tail",
          expr: {
            kind: "call",
            path: "Ok",
            args: [{
              kind: "binary",
              operator: "+",
              left: {
                kind: "index",
                receiver: { kind: "path", path: "values" },
                index: {
                  kind: "try",
                  errorDomain: "runtime",
                  expr: {
                    kind: "call",
                    path: "tsonic_rust_runtime::conversions::i32_to_usize",
                    args: [{ kind: "int-literal", text: "0" }],
                  },
                },
              },
              right: {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "call",
                  path: "tsonic_rust_runtime::conversions::usize_to_i32",
                  args: [{
                    kind: "method-call",
                    receiver: { kind: "path", path: "values" },
                    method: "len",
                    args: [],
                  }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /Ok\(values\[tsonic_rust_runtime::conversions::i32_to_usize\(0\)\?\]\n {8}\+ tsonic_rust_runtime::conversions::usize_to_i32\(values\.len\(\)\)\?\)/u,
  );
  assert.doesNotMatch(source, /Ok\(\n/u);
});

test("multi-argument calls follow rustfmt argument width independently of callable width", () => {
  const longArguments = {
    kind: "path",
    path: "__tsonic_callable_arguments_1",
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "tsonic_rust_node::buffer::Buffer::from_string_enc",
            args: [
              { kind: "str-literal", value: "ok" },
              { kind: "str-literal", value: "utf8" },
            ],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "handle",
            args: [
              { kind: "field", receiver: longArguments, name: "0" },
              { kind: "field", receiver: longArguments, name: "1" },
            ],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /tsonic_rust_node::buffer::Buffer::from_string_enc\("ok", "utf8"\);/u,
  );
  assert.match(
    source,
    /handle\(\n {8}__tsonic_callable_arguments_1\.0,\n {8}__tsonic_callable_arguments_1\.1,\n {4}\);/u,
  );
});

test("single projection calls keep a short receiver attached when closure arguments expand", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "projected",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "pair" },
            method: "project_member",
            args: [
              { kind: "str-literal", value: "stable.member.identity" },
              {
                kind: "closure",
                params: [{ name: "owner", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "field", receiver: { kind: "path", path: "owner" }, name: "state" },
                  method: "with",
                  args: [{
                    kind: "closure",
                    params: [{ name: "state", byRefCopy: false }],
                    body: { kind: "field", receiver: { kind: "path", path: "state" }, name: "0" },
                  }],
                },
              },
              {
                kind: "closure",
                params: [
                  { name: "owner", byRefCopy: false },
                  { name: "value", byRefCopy: false },
                ],
                body: {
                  kind: "method-call",
                  receiver: { kind: "field", receiver: { kind: "path", path: "owner" }, name: "state" },
                  method: "with_mut",
                  args: [{
                    kind: "closure",
                    params: [{ name: "state", byRefCopy: false }],
                    body: {
                      kind: "assignment",
                      target: { kind: "field", receiver: { kind: "path", path: "state" }, name: "0" },
                      value: { kind: "path", path: "value" },
                    },
                  }],
                },
              },
            ],
          },
        }],
      },
    }],
  });

  assert.match(source, /let projected = pair\.project_member\(\n/u);
  assert.match(source, /pair\.project_member\(\n {8}"stable\.member\.identity",/u);
  assert.doesNotMatch(source, /let projected = pair\n\s+\.project_member/u);
});

test("fallible calls on the left of comparisons expand their arguments before the operator", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "divide",
              args: [
                { kind: "call", path: "rt::BigInt::from_decimal_literal", args: [{ kind: "str-literal", value: "1" }] },
                { kind: "call", path: "rt::BigInt::from_decimal_literal", args: [{ kind: "str-literal", value: "0" }] },
              ],
            },
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "divide",
                  args: [
                    { kind: "call", path: "rt::BigInt::from_decimal_literal", args: [{ kind: "str-literal", value: "7" }] },
                    { kind: "call", path: "rt::BigInt::from_decimal_literal", args: [{ kind: "str-literal", value: "3" }] },
                  ],
                },
              },
              right: { kind: "call", path: "rt::BigInt::from_decimal_literal", args: [{ kind: "str-literal", value: "2" }] },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /divide\(\n {8}rt::BigInt::from_decimal_literal\("1"\),\n {8}rt::BigInt::from_decimal_literal\("0"\),\n {4}\)\?;/u);
  assert.match(source, /divide\(\n {12}rt::BigInt::from_decimal_literal\("7"\),\n {12}rt::BigInt::from_decimal_literal\("3"\),\n {8}\)\? ==/u);
});

test("fitting fallible call operands stay compact before a comparison break", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "try",
                expr: {
                  kind: "call",
                  path: "js_abi::string_search_regexp_native",
                  args: [{ kind: "str-literal", value: "hello" }, {
                    kind: "reference",
                    mutable: false,
                    expr: {
                      kind: "try",
                      expr: {
                        kind: "call",
                        path: "js_abi::regexp_new_native",
                        args: [
                          { kind: "str-literal", value: "z" },
                          { kind: "str-literal", value: "" },
                        ],
                      },
                    },
                  }],
                },
              },
              right: {
                kind: "unary",
                operator: "-",
                operand: { kind: "float-literal", text: "1234.0" },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /string_search_regexp_native\("hello", &js_abi::regexp_new_native\("z", ""\)\?\)\?\n {12}== -1234\.0/u,
  );
});

test("long calls on the left of comparisons expand before the operator", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "call",
                path: "rt::option_coalesce",
                args: [
                  {
                    kind: "try",
                    expr: {
                      kind: "call",
                      path: "length",
                      args: [{
                        kind: "call",
                        path: "Some",
                        args: [{
                          kind: "call",
                          path: "String::from",
                          args: [{ kind: "str-literal", value: "rust" }],
                        }],
                      }],
                    },
                  },
                  { kind: "path", path: "std::convert::identity" },
                  {
                    kind: "closure",
                    params: [],
                    body: {
                      kind: "unary",
                      operator: "-",
                      operand: { kind: "int-literal", text: "1" },
                    },
                  },
                ],
              },
              right: { kind: "int-literal", text: "4" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /rt::option_coalesce\(\n {12}length\(Some\(String::from\("rust"\)\)\)\?,\n {12}std::convert::identity,\n {12}\|\| -1,\n {8}\) == 4,/u,
  );
});

test("trailing closures expand to preserve comparison attachment", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "call",
                path: "rt::option_coalesce",
                args: [
                  {
                    kind: "method-call",
                    receiver: { kind: "path", path: "parts" },
                    method: "get_number",
                    args: [{ kind: "float-literal", text: "0.0" }],
                  },
                  { kind: "path", path: "std::convert::identity" },
                  {
                    kind: "closure",
                    params: [],
                    body: {
                      kind: "call",
                      path: "String::from",
                      args: [{ kind: "str-literal", value: "" }],
                    },
                  },
                ],
              },
              right: { kind: "str-literal", value: "a" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /rt::option_coalesce\(parts\.get_number\(0\.0\), std::convert::identity, \|\| \{\n {12}String::from\(""\)\n {8}\}\) == "a",/u,
  );
});

test("logical-chain operands keep fitted closures before nested comparison continuations", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "binary",
            operator: "&&",
            left: { kind: "bool-literal", value: true },
            right: {
              kind: "binary",
              operator: "==",
              left: {
                kind: "call",
                path: "rt::option_coalesce",
                args: [
                  {
                    kind: "method-call",
                    receiver: { kind: "path", path: "parts" },
                    method: "get_number",
                    args: [{ kind: "float-literal", text: "0.0" }],
                  },
                  { kind: "path", path: "std::convert::identity" },
                  {
                    kind: "closure",
                    params: [],
                    body: {
                      kind: "call",
                      path: "String::from",
                      args: [{ kind: "str-literal", value: "" }],
                    },
                  },
                ],
              },
              right: { kind: "str-literal", value: "a" },
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /true\n {8}&& rt::option_coalesce\(parts\.get_number\(0\.0\), std::convert::identity, \|\| String::from\(""\)\)\n {12}== "a";/u,
  );
});

test("unary expressions expand long nested calls before outer attachment", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "unary",
              operator: "!",
              operand: {
                kind: "call",
                path: "rt::option_coalesce",
                args: [
                  { kind: "call", path: "includes", args: [{ kind: "path", path: "None" }] },
                  { kind: "path", path: "std::convert::identity" },
                  {
                    kind: "closure",
                    params: [],
                    body: { kind: "bool-literal", value: false },
                  },
                ],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /acme_testing::check\(!rt::option_coalesce\(\n {8}includes\(None\),\n {8}std::convert::identity,\n {8}\|\| false,\n {4}\)\);/u,
  );
});

test("unary fallible calls retain rustfmt's attached outer-call layout", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "unary",
              operator: "!",
              operand: {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "call",
                  path: "js_abi::regexp_test_native",
                  args: [
                    {
                      kind: "reference",
                      expr: {
                        kind: "try",
                        errorDomain: "runtime",
                        expr: {
                          kind: "call",
                          path: "js_abi::regexp_new_native",
                          args: [
                            { kind: "str-literal", value: "ab+c" },
                            { kind: "str-literal", value: "i" },
                          ],
                        },
                      },
                    },
                    { kind: "str-literal", value: "XYZ" },
                  ],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /acme_testing::check\(!js_abi::regexp_test_native\(\n {8}&js_abi::regexp_new_native\("ab\+c", "i"\)\?,\n {8}"XYZ",\n {4}\)\?\);/u,
  );
});

test("unary block arguments remain attached to their outer calls", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "unary",
              operator: "!",
              operand: {
                kind: "block",
                bindings: [{
                  name: "matched",
                  value: { kind: "bool-literal", value: true },
                }],
                value: { kind: "path", path: "matched" },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /acme_testing::check\(!\{\n {8}let matched = true;\n {8}matched\n {4}\}\);/u,
  );
  assert.doesNotMatch(source, /acme_testing::check\(\n/u);
});

test("long atomic vectors use rustfmt-compatible element lines", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "values",
          mutable: false,
          init: {
            kind: "vec-literal",
            elements: ["first", "second", "third", "fourth"].map((value) => ({
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value }],
            })),
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let values = vec!\[\n {8}String::from\("first"\),\n {8}String::from\("second"\),\n {8}String::from\("third"\),\n {8}String::from\("fourth"\),\n {4}\];/u,
  );
});

test("fallible conversion wrappers own multiline callback method chains", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "method-call",
                receiver: {
                  kind: "try",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "values" },
                    method: "try_map_with_array",
                    args: [{
                      kind: "closure",
                      params: [
                        { name: "value", byRefCopy: false },
                        { name: "index", byRefCopy: false },
                        { name: "owner", byRefCopy: false },
                      ],
                      body: {
                        kind: "call",
                        path: "risky",
                        args: [{ kind: "path", path: "value" }],
                      },
                    }],
                  },
                },
                method: "len",
                args: [],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /usize_to_i32\(\n {8}values\n {12}\.try_map_with_array\(\|value, index, owner\| risky\(value\)\)\?\n {12}\.len\(\),\n {4}\)\?;/u,
  );
});

test("fallible conversion wrappers stay attached to one callback method", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "call",
                path: "tsonic_rust_runtime::conversions::isize_to_f64",
                args: [{
                  kind: "try",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "values" },
                    method: "try_find_index_with_index",
                    args: [{
                      kind: "closure",
                      params: [
                        { name: "value", byRefCopy: false },
                        { name: "_index", byRefCopy: false },
                      ],
                      body: {
                        kind: "call",
                        path: "Ok::<_, rt::TsonicError>",
                        args: [{
                          kind: "binary",
                          operator: "==",
                          left: {
                            kind: "try",
                            expr: {
                              kind: "call",
                              path: "risky",
                              args: [{ kind: "path", path: "value" }],
                            },
                          },
                          right: { kind: "int-literal", text: "2" },
                        }],
                      },
                    }],
                  },
                }],
              },
              right: { kind: "float-literal", text: "1.0" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /isize_to_f64\(values\.try_find_index_with_index\(\n {12}\|value, _index\| Ok::<_, rt::TsonicError>\(risky\(value\)\? == 2\),\n {8}\)\?\) == 1\.0,/u);
});

test("conversion wrappers retain rustfmt layout for one block-valued array argument", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "try",
            expr: {
              kind: "call",
              path: "tsonic_rust_runtime::conversions::usize_to_i32",
              args: [{
                kind: "method-call",
                receiver: { kind: "path", path: "values" },
                method: "push_many",
                args: [{
                  kind: "slice-literal",
                  elements: [{
                    kind: "block",
                    bindings: [{
                      name: "derived",
                      value: { kind: "call", path: "Derived::new", args: [] },
                    }],
                    value: {
                      kind: "struct-literal",
                      path: "Base",
                      fields: [{
                        name: "identity",
                        value: { kind: "field", receiver: { kind: "path", path: "derived" }, name: "identity" },
                      }],
                    },
                  }],
                }],
              }],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /usize_to_i32\(values\.push_many\(\[\{\n {8}let derived = Derived::new\(\);\n {8}Base \{\n {12}identity: derived\.identity,\n {8}\}\n {4}\}\]\)\)\?;/u);
});

test("method chains inside expanded call comparisons use argument indentation", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "acme_testing::check",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "pair" },
                  method: "load",
                  args: [],
                },
                method: "addLeft",
                args: [{
                  kind: "method-call",
                  receiver: {
                    kind: "field",
                    receiver: {
                      kind: "method-call",
                      receiver: { kind: "path", path: "pair" },
                      method: "load",
                      args: [],
                    },
                    name: "__tsonic_state",
                  },
                  method: "with",
                  args: [{
                    kind: "closure",
                    params: [{ name: "state", byRefCopy: false }],
                    body: { kind: "path", path: "state.1" },
                  }],
                }],
              },
              right: { kind: "int-literal", text: "10" },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /acme_testing::check\(\n        pair\.load\(\)\n            \.addLeft/u);
});

test("expanded call comparisons break short receiver chains before the first selector", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "expr",
          expr: {
            kind: "call",
            path: "require_value",
            args: [{
              kind: "binary",
              operator: "==",
              left: {
                kind: "method-call",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "executed" },
                  method: "as_ref",
                  args: [],
                },
                method: "map",
                args: [{
                  kind: "closure",
                  params: [{ name: "optional_receiver_2", byRefCopy: false }],
                  body: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "optional_receiver_2" },
                    method: "required_group",
                    args: [{ kind: "float-literal", text: "0.0" }],
                  },
                }],
              },
              right: {
                kind: "call",
                path: "Some",
                args: [{
                  kind: "call",
                  path: "String::from",
                  args: [{ kind: "string-literal", value: "ab12" }],
                }],
              },
            }, {
              kind: "call",
              path: "String::from",
              args: [{ kind: "string-literal", value: "exec whole match" }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /require_value\(\n {8}executed\n {12}\.as_ref\(\)\n {12}\.map/u);
});

test("expanded call arguments keep fitting optional closure chains attached", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "letter",
          mutable: false,
          init: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "item" },
                  method: "groups",
                  args: [],
                },
                method: "as_ref",
                args: [],
              },
              method: "and_then",
              args: [{
                kind: "closure",
                params: [{ name: "optional_receiver_13", byRefCopy: false }],
                body: {
                  kind: "call",
                  path: "js_abi::regexp_named_groups_get_native",
                  args: [
                    { kind: "path", path: "optional_receiver_13" },
                    { kind: "str-literal", value: "letter" },
                  ],
                },
              }],
            }, { kind: "path", path: "std::convert::identity" }, {
              kind: "closure",
              params: [],
              body: {
                kind: "call",
                path: "String::from",
                args: [{ kind: "str-literal", value: "" }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(source, /item\.groups\(\)\.as_ref\(\)\.and_then\(\|optional_receiver_13\| \{/u);
  assert.doesNotMatch(source, /item\n\s+\.groups/u);
});

test("every fitted call layout preserves exact call-site type arguments", () => {
  const errorType = { kind: "named", path: "rt::TsonicError" };
  const expandedValue = {
    kind: "block",
    bindings: [{
      name: "selected",
      value: {
        kind: "call",
        path: "load_selected_value",
        genericArguments: [{ kind: "type", type: { kind: "string" } }],
        args: [{ kind: "path", path: "input" }],
      },
    }],
    value: { kind: "path", path: "selected" },
  };
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      generics: emptyRustGenerics,
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "direct",
          mutable: false,
          init: {
            kind: "call",
            path: "Ok",
            genericArguments: [
              { kind: "type", type: { kind: "infer" } },
              { kind: "type", type: errorType },
            ],
            args: [expandedValue],
          },
        }, {
          kind: "let",
          name: "associated",
          mutable: false,
          init: {
            kind: "associated-call",
            owner: { kind: "named", path: "Factory" },
            method: "make",
            genericArguments: [{ kind: "type", type: { kind: "string" } }],
            args: [expandedValue],
          },
        }, {
          kind: "let",
          name: "method",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "values" },
            method: "convert",
            genericArguments: [{ kind: "type", type: { kind: "string" } }],
            args: [expandedValue],
          },
        }, {
          kind: "let",
          name: "nested",
          mutable: false,
          init: {
            kind: "call",
            path: "wrap",
            args: [{
              kind: "call",
              path: "Ok",
              genericArguments: [
                { kind: "type", type: { kind: "infer" } },
                { kind: "type", type: errorType },
              ],
              args: [expandedValue],
            }],
          },
        }, {
          kind: "tail",
          expr: {
            kind: "try",
            resultErrorType: errorType,
            operandErrorType: errorType,
            expr: {
              kind: "method-call",
              receiver: {
                kind: "method-call",
                receiver: { kind: "path", path: "values" },
                method: "map",
                args: [{
                  kind: "closure",
                  params: [{ name: "value", byRefCopy: false }],
                  body: {
                    kind: "call",
                    path: "Ok",
                    genericArguments: [
                      { kind: "type", type: { kind: "infer" } },
                      { kind: "type", type: errorType },
                    ],
                    args: [{
                      kind: "try",
                      resultErrorType: errorType,
                      operandErrorType: errorType,
                      expr: {
                        kind: "call",
                        path: "convert_value_with_an_intentionally_long_name",
                        args: [{ kind: "path", path: "value" }],
                      },
                    }],
                  },
                }],
              },
              method: "transpose",
              args: [],
            },
          },
        }],
      },
    }],
  });

  assert.match(source, /Ok::<_, rt::TsonicError>\(\{/u);
  assert.match(source, /Factory::make::<String>\(\{/u);
  assert.match(source, /values\.convert::<String>\(\{/u);
  assert.match(source, /wrap\(Ok::<_, rt::TsonicError>\(\{/u);
  assert.match(
    source,
    /\.map\(\|value\| \{\n {12}Ok::<_, rt::TsonicError>\(convert_value_with_an_intentionally_long_name\(value\)\?\)\n {8}\}\)/u,
  );
});
