import assert from "node:assert/strict";
import { test } from "node:test";

import { printRustSourceFile } from "../../../dist/print/source/index.js";

const headerComment = "Generated by the Tsonic Rust target. Do not edit.";

test("rustfmt-stable calls, closures, conditionals, and borrowed fallible chains", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "field_label",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: { kind: "path", path: "label" },
              method: "clone",
              args: [],
            }, {
              kind: "path",
              path: "std::convert::identity",
            }, {
              kind: "closure",
              params: [],
              body: {
                kind: "owned-string-from-borrowed-str",
                expression: { kind: "str-literal", value: "none" },
              },
            }],
          },
        }, {
          kind: "let",
          name: "loud",
          mutable: false,
          type: { kind: "string" },
          init: {
            kind: "conditional",
            condition: { kind: "path", path: "selected" },
            whenTrue: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "READY" }],
            },
            whenFalse: {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "SET" }],
            },
          },
        }, {
          kind: "expr",
          expr: {
            kind: "string-concat",
            parts: [{
              kind: "owned-string-from-borrowed-str",
              expression: { kind: "str-literal", value: ":" },
            }, {
              kind: "call",
              path: "rt::option_coalesce",
              args: [{
                kind: "field",
                receiver: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "values" },
                  method: "clone",
                  args: [],
                },
                name: "1",
              }, {
                kind: "path",
                path: "std::convert::identity",
              }, {
                kind: "closure",
                params: [],
                body: { kind: "string-literal", value: "none" },
              }],
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "string-concat",
            parts: [{
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }, {
              kind: "call",
              path: "rt::source_string",
              args: [{
                kind: "reference",
                expr: {
                  kind: "try",
                  errorDomain: "runtime",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "callable" },
                    method: "call",
                    args: [{
                      kind: "tuple-literal",
                      elements: [{
                        kind: "try",
                        errorDomain: "runtime",
                        expr: {
                          kind: "call",
                          path: "tsonic_rust_runtime::conversions::f64_to_i32",
                          args: [{ kind: "float-literal", text: "3.0" }],
                        },
                      }, {
                        kind: "call",
                        path: "Some",
                        args: [{
                          kind: "call",
                          path: "String::from",
                          args: [{ kind: "str-literal", value: "bound" }],
                        }],
                      }],
                    }],
                  },
                },
              }],
            }, {
              kind: "call",
              path: "String::from",
              args: [{ kind: "str-literal", value: "" }],
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "rt::option_coalesce",
            args: [{
              kind: "method-call",
              receiver: { kind: "path", path: "value" },
              method: "with",
              args: [{
                kind: "closure",
                params: [{ name: "state", mutable: false }],
                body: {
                  kind: "field",
                  receiver: { kind: "path", path: "state" },
                  name: "id",
                },
              }],
            }, {
              kind: "path",
              path: "Ok",
            }, {
              kind: "closure",
              params: [],
              body: {
                kind: "call",
                path: "tsonic_rust_runtime::conversions::f64_to_i32",
                args: [{ kind: "float-literal", text: "0.0" }],
              },
            }],
          },
        }, {
          kind: "expr",
          expr: {
            kind: "call",
            path: "call_bound",
            args: [{ kind: "path", path: "receiver" }, {
              kind: "associated-call",
              owner: {
                kind: "named",
                path: "rt::Callable",
                typeArguments: [{
                  kind: "tuple",
                  elements: [
                    { kind: "primitive", name: "i32" },
                    {
                      kind: "named",
                      path: "Option",
                      typeArguments: [{ kind: "string" }],
                    },
                  ],
                }, {
                  kind: "named",
                  path: "rt::TsonicResult",
                  typeArguments: [{ kind: "string" }],
                }],
              },
              method: "new",
              args: [{
                kind: "closure-block",
                params: [{ name: "callable_arguments", mutable: false }],
                move: true,
                async: false,
                body: {
                  statements: [{
                    kind: "tail",
                    expr: {
                      kind: "call",
                      path: "Ok::<_, rt::TsonicError>",
                      args: [{ kind: "path", path: "callable_arguments.1" }],
                    },
                  }],
                },
              }],
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let field_label: String =\n {8}rt::option_coalesce\(label\.clone\(\), std::convert::identity, \|\| String::from\("none"\)\);/u,
  );
  assert.match(
    source,
    /let loud: String = if selected \{\n {8}String::from\("READY"\)\n {4}\} else \{\n {8}String::from\("SET"\)\n {4}\};/u,
  );
  assert.match(
    source,
    /rt::option_coalesce\(values\.clone\(\)\.1, std::convert::identity, \|\| String::from\(\n {12}"none"\n {8}\)\),/u,
  );
  assert.match(source, /rt::source_string\(&callable\.call\(\(\n/u);
  assert.doesNotMatch(source, /rt::source_string\(&callable\n {8}\.call/u);
  assert.match(
    source,
    /rt::option_coalesce\(value\.with\(\|state\| state\.id\), Ok, \|\| \{\n {8}tsonic_rust_runtime::conversions::f64_to_i32\(0\.0\)\n {4}\}\);/u,
  );
  assert.match(
    source,
    /rt::Callable::<\(i32, Option<String>\), rt::TsonicResult<String>>::new\(/u,
  );
  assert.doesNotMatch(source, /rt::Callable::<\n/u);
});

test("typed bindings move a fitting fallible constructor chain to the continuation line", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "joined",
          mutable: false,
          type: { kind: "named", path: "js_abi::JsString" },
          init: {
            kind: "try",
            errorDomain: "runtime",
            expr: {
              kind: "method-call",
              receiver: {
                kind: "try",
                errorDomain: "runtime",
                expr: {
                  kind: "associated-call",
                  owner: { kind: "named", path: "js_abi::JsRegExp" },
                  method: "new",
                  args: [
                    { kind: "str-literal", value: "\\s+" },
                    { kind: "str-literal", value: "g" },
                  ],
                },
              },
              method: "replace",
              args: [
                { kind: "path", path: "value" },
                {
                  kind: "reference",
                  expr: {
                    kind: "associated-call",
                    owner: { kind: "named", path: "js_abi::JsString" },
                    method: "from",
                    args: [{ kind: "str-literal", value: "-" }],
                  },
                },
              ],
            },
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let joined: js_abi::JsString =\n {8}js_abi::JsRegExp::new\("\\\\s\+", "g"\)\?\.replace\(value, &js_abi::JsString::from\("-"\)\)\?;/u,
  );
});

test("near-width nested calls move below typed bindings before expansion", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "if",
          condition: { kind: "bool-literal", value: true },
          then: {
            statements: [{
              kind: "let",
              name: "digest",
              mutable: false,
              type: { kind: "named", path: "js_abi::JsString" },
              init: {
                kind: "call",
                path: "tsonic_rust_js::abi::js_string_from_utf8",
                args: [{
                  kind: "try",
                  errorDomain: "runtime",
                  expr: {
                    kind: "method-call",
                    receiver: { kind: "path", path: "mac" },
                    method: "digest_string",
                    args: [{
                      kind: "reference",
                      expr: {
                        kind: "call",
                        path: "tsonic_rust_js::abi::js_string_to_utf8",
                        args: [{
                          kind: "reference",
                          expr: {
                            kind: "associated-call",
                            owner: { kind: "named", path: "js_abi::JsString" },
                            method: "from",
                            args: [{ kind: "str-literal", value: "hex" }],
                          },
                        }],
                      },
                    }],
                  },
                }],
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /let digest: js_abi::JsString =\n {12}tsonic_rust_js::abi::js_string_from_utf8\(mac\.digest_string\(\n {16}&tsonic_rust_js::abi::js_string_to_utf8\(&js_abi::JsString::from\("hex"\)\),\n {12}\)\?\);/u,
  );
});

test("multiline block call arguments use their expanded argument depth", () => {
  const source = printRustSourceFile({
    headerComment,
    items: [{
      kind: "function",
      name: "proof",
      visibility: "public",
      params: [],
      body: {
        statements: [{
          kind: "let",
          name: "replaced",
          mutable: false,
          init: {
            kind: "method-call",
            receiver: { kind: "path", path: "expression" },
            method: "try_replace_with",
            args: [{ kind: "reference", expr: { kind: "path", path: "input" } }, {
              kind: "block",
              bindings: [{
                name: "replacement_callback",
                value: {
                  kind: "associated-call",
                  owner: {
                    kind: "named",
                    path: "rt::Callable",
                    typeArguments: [{
                      kind: "tuple",
                      elements: [
                        { kind: "named", path: "js_abi::JsString" },
                        { kind: "named", path: "js_abi::JsValue" },
                        { kind: "named", path: "js_abi::JsValue" },
                      ],
                    }, {
                      kind: "named",
                      path: "rt::TsonicResult",
                      typeArguments: [{ kind: "named", path: "js_abi::JsString" }],
                    }],
                  },
                  method: "new",
                  args: [{
                    kind: "closure",
                    move: true,
                    params: [{ name: "arguments", byRefCopy: false }],
                    body: { kind: "path", path: "Ok(arguments.0)" },
                  }],
                },
              }],
              value: {
                kind: "closure",
                move: true,
                params: [{ name: "replacement_arguments", byRefCopy: false }],
                body: {
                  kind: "method-call",
                  receiver: { kind: "path", path: "replacement_callback" },
                  method: "call",
                  args: [{
                    kind: "tuple-literal",
                    elements: [{
                      kind: "call",
                      path: "js_abi::regexp_replacement_argument_string",
                      args: [{
                        kind: "reference",
                        expr: { kind: "path", path: "replacement_arguments" },
                      }, { kind: "int-literal", text: "0" }],
                    }, {
                      kind: "call",
                      path: "js_abi::regexp_replacement_argument_value",
                      args: [{
                        kind: "reference",
                        expr: { kind: "path", path: "replacement_arguments" },
                      }, { kind: "int-literal", text: "1" }],
                    }],
                  }],
                },
              },
            }],
          },
        }],
      },
    }],
  });

  assert.match(
    source,
    /\.try_replace_with\(&input, \{\n {8}let replacement_callback = rt::Callable/u,
  );
  assert.match(
    source,
    /\n {8}move \|replacement_arguments\| \{\n {12}replacement_callback\.call/u,
  );
  assert.match(source, /\n {4}\}\);/u);
});
