use rustc_hir::def::{CtorKind, CtorOf, DefKind};

pub fn definition_kind(kind: DefKind) -> &'static str {
    match kind {
        DefKind::Mod => "module",
        DefKind::Struct => "struct",
        DefKind::Union => "union",
        DefKind::Enum => "enum",
        DefKind::Variant => "variant",
        DefKind::Trait => "trait",
        DefKind::TyAlias => "type-alias",
        DefKind::ForeignTy => "foreign-type",
        DefKind::TraitAlias => "trait-alias",
        DefKind::AssocTy => "associated-type",
        DefKind::TyParam => "type-parameter",
        DefKind::Fn => "function",
        DefKind::Const { .. } => "constant",
        DefKind::ConstParam => "const-parameter",
        DefKind::Static { .. } => "static",
        DefKind::Ctor(CtorOf::Struct, CtorKind::Fn) => "tuple-struct-constructor",
        DefKind::Ctor(CtorOf::Struct, CtorKind::Const) => "unit-struct-constructor",
        DefKind::Ctor(CtorOf::Variant, CtorKind::Fn) => "tuple-variant-constructor",
        DefKind::Ctor(CtorOf::Variant, CtorKind::Const) => "unit-variant-constructor",
        DefKind::AssocFn => "associated-function",
        DefKind::AssocConst { .. } => "associated-constant",
        DefKind::Macro(_) => "macro",
        DefKind::ExternCrate => "extern-crate",
        DefKind::Use => "use",
        DefKind::ForeignMod => "foreign-module",
        DefKind::AnonConst => "anonymous-constant",
        DefKind::InlineConst => "inline-constant",
        DefKind::OpaqueTy => "opaque-type",
        DefKind::Field => "field",
        DefKind::LifetimeParam => "lifetime-parameter",
        DefKind::GlobalAsm => "global-assembly",
        DefKind::Impl { of_trait: true } => "trait-implementation",
        DefKind::Impl { of_trait: false } => "inherent-implementation",
        DefKind::Closure => "closure",
        DefKind::SyntheticCoroutineBody => "coroutine-body",
    }
}
