export {
  canonicalCompilerTypePathKey,
  canonicalPathKey,
  compareCompilerGenericParameters,
  exactAssociatedTypeIdentity,
  genericParameterMap,
  normalizeGenerics,
  normalizePathArguments,
  normalizeRustCompilerBound,
  normalizeTraitReference,
  normalizeType,
  standardTypePathKind,
  type RustCompilerNormalizationContext,
} from "./types/normalization.js";
export {
  compilerTypeSupportsTrait,
  compilerTypeTraitConditions,
  directImplementationGenericBindings,
  normalizeTypeTraits,
  rustCompilerTraitByCanonicalPath,
  typeParameterGuaranteesTrait,
} from "./types/requirements.js";
export {
  emptyRustCompilerSubstitutions,
  rustCompilerTraitSemanticKey,
  rustCompilerTypeArguments,
  rustCompilerTypeSemanticKey,
  rustCompilerTypesEqual,
  rustStaticValueCanBeCopied,
  substituteRustCompilerArgument,
  substituteRustCompilerBound,
  substituteRustCompilerConstExpression,
  substituteRustCompilerGenerics,
  substituteRustCompilerType,
  type RustCompilerSubstitutions,
} from "./types/substitution.js";
