export type {
  RustTargetAssociatedConstraint,
  RustTargetConstArgument,
  RustTargetGenericArgument,
  RustTargetGenericParameter,
  RustTargetTraitRef,
  TargetTypeRef,
} from "./model.js";
export {
  rustConstGenericArgument,
  rustLifetimeGenericArgument,
  rustOnlyTypeGenericArguments,
  rustTargetConstArguments,
  rustTargetConstSafeInteger,
  rustTargetGenericBindingsForArguments,
  rustTargetGenericTypeArguments,
  rustTargetLifetimeArguments,
  rustTypeGenericArgument,
  rustTypeGenericArguments,
} from "./generic-arguments.js";
export type { RustPrimitiveTypeName } from "../syntax/tokens.js";
export {
  getRustGeneratorProtocol,
  getRustIteratorResultProtocol,
  isRustCallableCarrier,
  isRustLocationCarrier,
  rustAsyncGeneratorTargetType,
  rustCallableProtocol,
  rustCallableTargetType,
  rustClosureProtocol,
  rustClosureTargetType,
  rustGeneratorTargetType,
  rustGeneratorStorageTargetType,
  rustIteratorResultTargetType,
  rustLocationPointeeCarrier,
  rustLocationTargetType,
  rustNativeCallableProtocol,
  rustOptionalLocationPointeeCarrier,
  rustStructuralMethodCallableCarrier,
  rustStructuralMethodStorageCarrier,
  rustStructuralPropertyGetterStorageCarrier,
  rustStructuralPropertySetterStorageCarrier,
  rustStructuralPropertyValueCarrier,
} from "./carriers/callables.js";
export type { RustGeneratorProtocol, RustIteratorResultProtocol } from "./carriers/callables.js";
export {
  getRustJsMapTargetTypes,
  getRustJsSetElementTargetType,
  isRustBigIntCarrier,
  isRustBoolCarrier,
  isRustJsArrayCarrier,
  isRustJsArrayLikeCarrier,
  isRustJsStringCarrier,
  isRustJsValueCarrier,
  isRustNeverCarrier,
  isRustNullCarrier,
  isRustProgramErrorCarrier,
  isRustStringCarrier,
  isRustUndefinedCarrier,
  isRustUnitCarrier,
  isRustVecCarrier,
  rustJsArrayConcatItemTargetType,
  rustJsArrayLikeElementTargetType,
  rustJsArrayLikeIterationElementTargetType,
  rustJsArrayTargetType,
  rustJsDateTargetType,
  rustJsErrorTargetType,
  rustJsMapTargetType,
  rustJsRegExpExecArrayTargetType,
  rustJsRegExpIndicesTargetType,
  rustJsRegExpMatchArrayTargetType,
  rustJsRegExpNamedGroupsTargetType,
  rustJsRegExpNamedIndicesTargetType,
  rustJsRegExpStringIteratorTargetType,
  rustJsRegExpTargetType,
  rustJsSetTargetType,
  rustJsStringTargetType,
  rustJsValueTargetType,
  rustProgramErrorTargetType,
  rustRegExpExecArrayTargetType,
  rustRegExpIndicesTargetType,
  rustRegExpMatchArrayTargetType,
  rustRegExpNamedGroupsTargetType,
  rustRegExpNamedIndicesTargetType,
  rustRegExpStringIteratorTargetType,
} from "./carriers/js.js";
export {
  isRustOptionCarrier,
  rustOptionElementCarrier,
  rustOptionTargetType,
} from "./carriers/optional.js";
export {
  isRustNamedTypeTraitContract,
  rustBigIntTargetType,
  rustBorrowedStrTargetType,
  rustFixedArrayCarrierValue,
  rustFixedArrayTargetType,
  rustMoveOnlyNamedTypeTraits,
  rustNamedTargetType,
  rustNamedTypeCarrierValue,
  rustNeverTargetType,
  rustNullTargetType,
  rustSourcePrimitiveTargetType,
  rustStringTargetType,
  rustTupleTargetType,
  rustUndefinedTargetType,
  rustUnitTargetType,
  rustVecTargetType,
} from "./carriers/native.js";
export type {
  RustFixedArrayCarrierValue,
  RustNamedTypeCarrierValue,
} from "./carriers/native.js";
export type {
  RustNamedTypeTraitContract,
  RustNamedTypeTraitImplementation,
  RustNamedTypeTraitRequirement,
} from "./model.js";
export {
  isRustDefinitelyNullishCarrier,
  isRustIntegerCarrier,
  isRustNullishSourceCarrier,
  isRustNumericCarrier,
  isRustSignedNumericCarrier,
  isRustSliceMutRefCarrier,
  isRustSliceRefCarrier,
  rustFutureOutputCarrier,
  rustFutureTargetId,
  rustFutureTargetType,
  rustNullishSourceTargetType,
  rustPrimitiveTypeName,
  rustSliceElementCarrier,
  rustSliceMutRefTargetType,
  rustSliceRefTargetType,
  sameRustPrimitiveCarrier,
} from "./carriers/primitives.js";
export {
  rustAsyncGeneratorTargetId,
  rustBorrowedAsyncGeneratorTargetId,
  rustBorrowedGeneratorTargetId,
  rustBigIntTargetId,
  rustCallableTargetId,
  rustGeneratorTargetId,
  rustIteratorResultTargetId,
  rustJsArrayConcatItemTargetId,
  rustJsArrayTargetId,
  rustJsDateTargetId,
  rustJsErrorTargetId,
  rustJsMapTargetId,
  rustJsRegExpExecArrayTargetId,
  rustJsRegExpIndicesTargetId,
  rustJsRegExpMatchArrayTargetId,
  rustJsRegExpNamedGroupsTargetId,
  rustJsRegExpNamedIndicesTargetId,
  rustJsRegExpStringIteratorTargetId,
  rustJsRegExpTargetId,
  rustJsSetTargetId,
  rustJsStringTargetId,
  rustJsValueTargetId,
  rustLocationTargetId,
  rustNamedTypeCarrierName,
  rustNeverCarrierName,
  rustNullTargetId,
  rustOptionTargetId,
  rustProgramErrorTargetId,
  rustRegExpExecArrayTargetId,
  rustRegExpIndicesTargetId,
  rustRegExpMatchArrayTargetId,
  rustRegExpNamedGroupsTargetId,
  rustRegExpNamedIndicesTargetId,
  rustRegExpStringIteratorTargetId,
  rustSourceTypeCarrier,
  rustSourceTypeCarrierValue,
  rustSourceUnionCarrierName,
  rustSourceUnionCarrierValue,
  rustSourceUnionTargetType,
  rustStringTargetId,
  rustStructuralObjectCarrierName,
  rustStructuralObjectCarrierValue,
  rustStructuralObjectTargetType,
  rustUndefinedTargetId,
} from "./carriers/source-types.js";
export type {
  RustSourceTypeCarrierValue,
  RustSourceUnionCarrierValue,
  RustSourceUnionVariantCarrierValue,
  RustStructuralObjectCarrierValue,
  RustStructuralObjectFieldCarrierValue,
} from "./carriers/source-types.js";
export {
  inferRustTargetGenericBindings,
  inferRustTargetTypeParameterBindings,
} from "./carriers/generic-inference.js";
export type {
  RustTargetGenericBindings,
  RustTargetGenericInferenceOptions,
  RustTargetGenericParameterSet,
} from "./carriers/generic-inference.js";
export {
  rustTargetGenericReferences,
  rustTargetTypeContainsTypeParameter,
  rustTargetTypeParameterNames,
} from "./carriers/generic-references.js";
export type { RustTargetGenericReferences } from "./carriers/generic-references.js";
export {
  substituteRustTargetGenericArgument,
  substituteRustTargetGenerics,
  substituteRustTargetTypeParameters,
} from "./carriers/substitution.js";
export {
  isRustCopyCarrier,
  isRustJsStrictEqualityCarrier,
  isRustSourceStringConvertibleCarrier,
  rustCarrierSupportsClone,
  rustCarrierReferentMutationRequiresMutableBinding,
  rustCarrierSupportsJsEquality,
  rustCarrierSupportsTrait,
} from "./carriers/traits.js";
