// Structured Rust output model. The printer is the only place that turns this
// model into text. Slice R1 only ever produces empty crate roots; items arrive
// with the first fact-backed lowering slice.

export interface RustSourceFileModel {
  readonly kind: "rust-source-file";
  readonly headerComment: string;
  readonly hasMainFunction: boolean;
}

export function createEmptyRustLibraryFile(): RustSourceFileModel {
  return {
    kind: "rust-source-file",
    headerComment: "Generated by the Tsonic Rust target. Do not edit.",
    hasMainFunction: false,
  };
}

export function createEmptyRustBinaryFile(): RustSourceFileModel {
  return {
    kind: "rust-source-file",
    headerComment: "Generated by the Tsonic Rust target. Do not edit.",
    hasMainFunction: true,
  };
}
