// Structured Rust output model for the static-native construct set. The
// printer is the only place this model becomes text.

export type RustType =
  | { readonly kind: "primitive"; readonly name: string }
  | { readonly kind: "string" }
  | { readonly kind: "unit" }
  | { readonly kind: "named"; readonly path: string; readonly typeArguments?: readonly RustType[] }
  | { readonly kind: "slice-ref"; readonly element: RustType; readonly mutable: boolean }
  | { readonly kind: "tuple"; readonly elements: readonly RustType[] };

export type RustExpr =
  | { readonly kind: "int-literal"; readonly text: string }
  | { readonly kind: "float-literal"; readonly text: string }
  | { readonly kind: "bool-literal"; readonly value: boolean }
  | { readonly kind: "string-literal"; readonly value: string }
  | { readonly kind: "str-literal"; readonly value: string }
  | { readonly kind: "path"; readonly path: string }
  | { readonly kind: "unary"; readonly operator: "-" | "!"; readonly operand: RustExpr }
  | { readonly kind: "binary"; readonly operator: string; readonly left: RustExpr; readonly right: RustExpr }
  | { readonly kind: "call"; readonly path: string; readonly args: readonly RustExpr[] }
  | { readonly kind: "method-call"; readonly receiver: RustExpr; readonly method: string; readonly args: readonly RustExpr[] }
  | { readonly kind: "field"; readonly receiver: RustExpr; readonly name: string }
  | { readonly kind: "index"; readonly receiver: RustExpr; readonly index: RustExpr }
  | { readonly kind: "string-concat"; readonly parts: readonly RustExpr[] }
  | { readonly kind: "cast"; readonly expr: RustExpr; readonly to: string }
  | { readonly kind: "reference"; readonly expr: RustExpr; readonly mutable?: boolean }
  | { readonly kind: "vec-literal"; readonly elements: readonly RustExpr[] }
  | { readonly kind: "struct-literal"; readonly path: string; readonly fields: readonly { readonly name: string; readonly value: RustExpr }[] }
  | { readonly kind: "tuple-literal"; readonly elements: readonly RustExpr[] };

export type RustStmt =
  | { readonly kind: "let"; readonly name: string; readonly mutable: boolean; readonly type?: RustType; readonly init: RustExpr }
  | { readonly kind: "expr"; readonly expr: RustExpr }
  | { readonly kind: "assign"; readonly target: RustExpr; readonly operator: string; readonly value: RustExpr }
  | { readonly kind: "return"; readonly expr?: RustExpr }
  | { readonly kind: "tail"; readonly expr: RustExpr }
  | { readonly kind: "if"; readonly condition: RustExpr; readonly then: RustBlock; readonly else?: RustBlock }
  | { readonly kind: "while"; readonly condition: RustExpr; readonly body: RustBlock }
  | { readonly kind: "for"; readonly binding: string; readonly iterable: RustExpr; readonly body: RustBlock }
  | { readonly kind: "index-assign"; readonly receiver: RustExpr; readonly index: RustExpr; readonly value: RustExpr }
  | { readonly kind: "scope"; readonly body: RustBlock };

export interface RustBlock {
  readonly statements: readonly RustStmt[];
}

export interface RustFunctionParam {
  readonly name: string;
  readonly type: RustType;
  readonly mutable?: boolean;
}

export type RustSelfParam = "ref" | "mut-ref";

export interface RustStructField {
  readonly name: string;
  readonly type: RustType;
}

export interface RustImplFunction {
  readonly name: string;
  readonly pub: boolean;
  readonly selfParam?: RustSelfParam;
  readonly params: readonly RustFunctionParam[];
  readonly returnType?: RustType;
  readonly body: RustBlock;
}

export type RustItem =
  | {
      readonly kind: "function";
      readonly name: string;
      readonly pub: boolean;
      readonly typeParams?: readonly string[];
      readonly params: readonly RustFunctionParam[];
      readonly returnType?: RustType;
      readonly body: RustBlock;
    }
  | {
      readonly kind: "const";
      readonly name: string;
      readonly pub: boolean;
      readonly type: RustType;
      readonly value: RustExpr;
    }
  | { readonly kind: "mod-decl"; readonly name: string; readonly pub: boolean }
  | { readonly kind: "struct"; readonly name: string; readonly pub: boolean; readonly derives: readonly string[]; readonly fields: readonly RustStructField[] }
  | { readonly kind: "impl"; readonly name: string; readonly functions: readonly RustImplFunction[] }
  | { readonly kind: "enum"; readonly name: string; readonly pub: boolean; readonly derives: readonly string[]; readonly variants: readonly { readonly name: string; readonly discriminant?: string }[] }
  | { readonly kind: "use"; readonly path: string; readonly alias?: string };

export interface RustSourceFileModel {
  readonly headerComment: string;
  readonly items: readonly RustItem[];
}

export const rustGeneratedHeaderComment = "Generated by the Tsonic Rust target. Do not edit.";

export function createRustSourceFile(items: readonly RustItem[]): RustSourceFileModel {
  return { headerComment: rustGeneratedHeaderComment, items };
}
