// Structured Rust output model for the R2 static-native spine. The printer is
// the only place this model becomes text.

export type RustType =
  | { readonly kind: "primitive"; readonly name: string }
  | { readonly kind: "string" }
  | { readonly kind: "unit" };

export type RustExpr =
  | { readonly kind: "int-literal"; readonly text: string }
  | { readonly kind: "float-literal"; readonly text: string }
  | { readonly kind: "bool-literal"; readonly value: boolean }
  | { readonly kind: "string-literal"; readonly value: string }
  | { readonly kind: "path"; readonly path: string }
  | { readonly kind: "unary"; readonly operator: "-" | "!"; readonly operand: RustExpr }
  | { readonly kind: "binary"; readonly operator: string; readonly left: RustExpr; readonly right: RustExpr }
  | { readonly kind: "call"; readonly path: string; readonly args: readonly RustExpr[] }
  | { readonly kind: "method-call"; readonly receiver: RustExpr; readonly method: string; readonly args: readonly RustExpr[] }
  | { readonly kind: "field"; readonly receiver: RustExpr; readonly name: string }
  | { readonly kind: "index"; readonly receiver: RustExpr; readonly index: RustExpr }
  | { readonly kind: "string-concat"; readonly parts: readonly RustExpr[] };

export type RustStmt =
  | { readonly kind: "let"; readonly name: string; readonly mutable: boolean; readonly type?: RustType; readonly init: RustExpr }
  | { readonly kind: "expr"; readonly expr: RustExpr }
  | { readonly kind: "assign"; readonly target: string; readonly operator: "=" | "+=" | "-="; readonly value: RustExpr }
  | { readonly kind: "return"; readonly expr?: RustExpr }
  | { readonly kind: "tail"; readonly expr: RustExpr }
  | { readonly kind: "if"; readonly condition: RustExpr; readonly then: RustBlock; readonly else?: RustBlock }
  | { readonly kind: "while"; readonly condition: RustExpr; readonly body: RustBlock }
  | { readonly kind: "scope"; readonly body: RustBlock };

export interface RustBlock {
  readonly statements: readonly RustStmt[];
}

export interface RustFunctionParam {
  readonly name: string;
  readonly type: RustType;
}

export type RustItem =
  | {
      readonly kind: "function";
      readonly name: string;
      readonly pub: boolean;
      readonly params: readonly RustFunctionParam[];
      readonly returnType?: RustType;
      readonly body: RustBlock;
    }
  | {
      readonly kind: "const";
      readonly name: string;
      readonly pub: boolean;
      readonly type: RustType;
      readonly value: RustExpr;
    }
  | { readonly kind: "mod-decl"; readonly name: string; readonly pub: boolean };

export interface RustSourceFileModel {
  readonly headerComment: string;
  readonly items: readonly RustItem[];
}

export const rustGeneratedHeaderComment = "Generated by the Tsonic Rust target. Do not edit.";

export function createRustSourceFile(items: readonly RustItem[]): RustSourceFileModel {
  return { headerComment: rustGeneratedHeaderComment, items };
}
