export const rustAuthoredSourceInnerAttributes = Object.freeze([
  "#![allow(non_snake_case)]",
  "#![allow(private_interfaces)]",
  "#![allow(unused_assignments, unused_variables)]",
  "#![allow(clippy::blocks_in_conditions)]",
  "#![allow(clippy::collapsible_if)]",
  "#![allow(clippy::comparison_to_empty)]",
  "#![allow(clippy::format_in_format_args)]",
  "#![allow(clippy::manual_range_contains)]",
  "#![allow(clippy::needless_question_mark)]",
  "#![allow(clippy::needless_return)]",
  "#![allow(clippy::never_loop)]",
  "#![allow(clippy::nonminimal_bool)]",
  "#![allow(clippy::redundant_closure)]",
  "#![allow(clippy::too_many_arguments)]",
  "#![allow(clippy::to_string_in_format_args)]",
  "#![allow(clippy::type_complexity)]",
  "#![allow(clippy::unnecessary_to_owned)]",
]);
