import {
  rustAsyncGeneratorTargetId,
  rustBigIntTargetId,
  rustBorrowedAsyncGeneratorTargetId,
  rustBorrowedGeneratorTargetId,
  rustCallableTargetId,
  rustGeneratorTargetId,
  rustIteratorResultTargetId,
  rustJsArrayBufferTargetId,
  rustJsArrayConcatItemTargetId,
  rustJsArrayTargetId,
  rustJsDataViewTargetId,
  rustJsDateTargetId,
  rustJsErrorTargetId,
  rustJsFloat32ArrayTargetId,
  rustJsFloat64ArrayTargetId,
  rustJsInt16ArrayTargetId,
  rustJsInt32ArrayTargetId,
  rustJsInt8ArrayTargetId,
  rustJsIntlCollatorTargetId,
  rustJsIntlDateTimeFormatPartTargetId,
  rustJsIntlDateTimeFormatTargetId,
  rustJsIntlNumberFormatPartTargetId,
  rustJsIntlNumberFormatTargetId,
  rustJsIntlResolvedCollatorOptionsTargetId,
  rustJsIntlResolvedDateTimeFormatOptionsTargetId,
  rustJsIntlResolvedNumberFormatOptionsTargetId,
  rustJsMapTargetId,
  rustJsPromiseFulfilledResultTargetId,
  rustJsPromiseRejectedResultTargetId,
  rustJsPromiseSettledResultTargetId,
  rustJsPromiseTargetId,
  rustJsRegExpExecArrayTargetId,
  rustJsRegExpIndicesTargetId,
  rustJsRegExpMatchArrayTargetId,
  rustJsRegExpNamedGroupsTargetId,
  rustJsRegExpNamedIndicesTargetId,
  rustJsRegExpStringIteratorTargetId,
  rustJsRegExpTargetId,
  rustJsSetTargetId,
  rustJsStringTargetId,
  rustJsSymbolTargetId,
  rustJsUint16ArrayTargetId,
  rustJsUint32ArrayTargetId,
  rustJsUint8ArrayTargetId,
  rustJsUint8ClampedArrayTargetId,
  rustJsValueTargetId,
  rustJsWeakMapTargetId,
  rustJsWeakSetTargetId,
  rustLocationTargetId,
  rustNullTargetId,
  rustOptionTargetId,
  rustProgramErrorTargetId,
  rustRegExpExecArrayTargetId,
  rustRegExpIndicesTargetId,
  rustRegExpMatchArrayTargetId,
  rustRegExpNamedGroupsTargetId,
  rustRegExpNamedIndicesTargetId,
  rustRegExpStringIteratorTargetId,
  rustStringTargetId,
  rustStrTargetId,
  rustTsValueTargetId,
  rustUndefinedTargetId,
} from "./source-types.js";

export const rustBuiltInCarrierRenderPaths: Readonly<Record<string, string>> = Object.freeze({
  [rustBigIntTargetId]: "rt::BigInt",
  [rustOptionTargetId]: "Option",
  [rustLocationTargetId]: "rt::Location",
  [rustGeneratorTargetId]: "rt::Generator",
  [rustAsyncGeneratorTargetId]: "rt::AsyncGenerator",
  [rustBorrowedGeneratorTargetId]: "rt::BorrowedGenerator",
  [rustBorrowedAsyncGeneratorTargetId]: "rt::BorrowedAsyncGenerator",
  [rustIteratorResultTargetId]: "rt::IteratorResult",
  [rustNullTargetId]: "rt::Null",
  [rustUndefinedTargetId]: "rt::Undefined",
  [rustJsErrorTargetId]: "rt::JsError",
  [rustProgramErrorTargetId]: "rt::TsonicError",
  [rustTsValueTargetId]: "rt::TsValue",
  [rustJsValueTargetId]: "js_abi::JsValue",
  [rustJsArrayTargetId]: "js_abi::JsArray",
  [rustJsArrayConcatItemTargetId]: "js_abi::JsArrayConcatItem",
  [rustJsMapTargetId]: "js_abi::JsMap",
  [rustJsPromiseTargetId]: "js_abi::JsPromise",
  [rustJsPromiseFulfilledResultTargetId]: "js_abi::PromiseFulfilledResult",
  [rustJsPromiseRejectedResultTargetId]: "js_abi::PromiseRejectedResult",
  [rustJsPromiseSettledResultTargetId]: "js_abi::PromiseSettledResult",
  [rustJsSetTargetId]: "js_abi::JsSet",
  [rustJsDateTargetId]: "js_abi::JsDate",
  [rustJsSymbolTargetId]: "js_abi::JsSymbol",
  [rustJsWeakMapTargetId]: "js_abi::JsWeakMap",
  [rustJsWeakSetTargetId]: "js_abi::JsWeakSet",
  [rustJsArrayBufferTargetId]: "js_abi::ArrayBuffer",
  [rustJsDataViewTargetId]: "js_abi::DataView",
  [rustJsInt8ArrayTargetId]: "js_abi::Int8Array",
  [rustJsUint8ArrayTargetId]: "js_abi::Uint8Array",
  [rustJsUint8ClampedArrayTargetId]: "js_abi::Uint8ClampedArray",
  [rustJsInt16ArrayTargetId]: "js_abi::Int16Array",
  [rustJsUint16ArrayTargetId]: "js_abi::Uint16Array",
  [rustJsInt32ArrayTargetId]: "js_abi::Int32Array",
  [rustJsUint32ArrayTargetId]: "js_abi::Uint32Array",
  [rustJsFloat32ArrayTargetId]: "js_abi::Float32Array",
  [rustJsFloat64ArrayTargetId]: "js_abi::Float64Array",
  [rustJsIntlDateTimeFormatTargetId]: "js_abi::IntlDateTimeFormat",
  [rustJsIntlNumberFormatTargetId]: "js_abi::IntlNumberFormat",
  [rustJsIntlCollatorTargetId]: "js_abi::IntlCollator",
  [rustJsIntlDateTimeFormatPartTargetId]: "js_abi::IntlDateTimeFormatPart",
  [rustJsIntlNumberFormatPartTargetId]: "js_abi::IntlNumberFormatPart",
  [rustJsIntlResolvedDateTimeFormatOptionsTargetId]: "js_abi::IntlResolvedDateTimeFormatOptions",
  [rustJsIntlResolvedNumberFormatOptionsTargetId]: "js_abi::IntlResolvedNumberFormatOptions",
  [rustJsIntlResolvedCollatorOptionsTargetId]: "js_abi::IntlResolvedCollatorOptions",
  [rustJsStringTargetId]: "js_abi::JsString",
  [rustJsRegExpTargetId]: "js_abi::JsRegExp",
  [rustRegExpExecArrayTargetId]: "js_abi::RegExpExecArray",
  [rustJsRegExpExecArrayTargetId]: "js_abi::JsRegExpExecArray",
  [rustRegExpMatchArrayTargetId]: "js_abi::RegExpMatchArray",
  [rustJsRegExpMatchArrayTargetId]: "js_abi::JsRegExpMatchArray",
  [rustRegExpIndicesTargetId]: "js_abi::RegExpIndices",
  [rustJsRegExpIndicesTargetId]: "js_abi::JsRegExpIndices",
  [rustRegExpNamedGroupsTargetId]: "js_abi::RegExpNamedGroups",
  [rustJsRegExpNamedGroupsTargetId]: "js_abi::JsRegExpNamedGroups",
  [rustRegExpNamedIndicesTargetId]: "js_abi::RegExpNamedIndices",
  [rustJsRegExpNamedIndicesTargetId]: "js_abi::JsRegExpNamedIndices",
  [rustRegExpStringIteratorTargetId]: "js_abi::RegExpStringIterator",
  [rustJsRegExpStringIteratorTargetId]: "js_abi::JsRegExpStringIterator",
});

const rustBuiltInTargetCarrierIds: ReadonlySet<string> = new Set([
  rustStringTargetId,
  rustStrTargetId,
  rustCallableTargetId,
  ...Object.keys(rustBuiltInCarrierRenderPaths),
]);

export function isRustBuiltInTargetCarrierId(id: string): boolean {
  return rustBuiltInTargetCarrierIds.has(id);
}
